// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PLC通讯基础控件项目.控件类基.PLC基础接口.PLC基础实现类.PLC报警控件保存类;

#nullable disable

namespace PLC通讯基础控件项目.Migrations
{
    [DbContext(typeof(PoliceContext))]
    partial class PoliceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("PLC通讯基础控件项目.控件类基.PLC基础接口.PLC报警控件保存类.EventMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("位触发条件")
                        .HasColumnType("INTEGER");

                    b.Property<string>("字触发条件")
                        .HasColumnType("TEXT");

                    b.Property<string>("字触发条件_具体")
                        .HasColumnType("TEXT");

                    b.Property<string>("报警内容")
                        .HasColumnType("TEXT");

                    b.Property<string>("报警发生时间")
                        .HasColumnType("TEXT");

                    b.Property<string>("报警处理时间")
                        .HasColumnType("TEXT");

                    b.Property<int>("类型")
                        .HasColumnType("INTEGER");

                    b.Property<string>("设备")
                        .HasColumnType("TEXT");

                    b.Property<string>("设备_具体地址")
                        .HasColumnType("TEXT");

                    b.Property<string>("设备_地址")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("EventMessage");
                });

            modelBuilder.Entity("PLC通讯基础控件项目.控件类基.PLC基础接口.PLC基础实现类.PLC报警控件保存类.EventHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("位触发条件")
                        .HasColumnType("INTEGER");

                    b.Property<string>("字触发条件")
                        .HasColumnType("TEXT");

                    b.Property<string>("字触发条件_具体")
                        .HasColumnType("TEXT");

                    b.Property<string>("报警内容")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("报警发生时间")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("报警处理时间")
                        .HasColumnType("TEXT");

                    b.Property<int>("类型")
                        .HasColumnType("INTEGER");

                    b.Property<string>("设备")
                        .HasColumnType("TEXT");

                    b.Property<string>("设备_具体地址")
                        .HasColumnType("TEXT");

                    b.Property<string>("设备_地址")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("EventHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
