
namespace PLC通讯基础控件项目.模板与控制界面.一区手动界面
{
    partial class ZDP1手动界面
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.daUiButton27 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton26 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton25 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton23 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton12 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton13 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton14 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton15 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton4 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton5 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton2 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton3 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton1 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton31 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.uiPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // uiPanel1
            // 
            this.uiPanel1.Controls.Add(this.daUiButton23);
            this.uiPanel1.Controls.Add(this.daUiButton12);
            this.uiPanel1.Controls.Add(this.daUiButton13);
            this.uiPanel1.Controls.Add(this.daUiButton1);
            this.uiPanel1.Controls.Add(this.daUiButton14);
            this.uiPanel1.Controls.Add(this.daUiButton31);
            this.uiPanel1.Controls.Add(this.daUiButton15);
            this.uiPanel1.Controls.Add(this.daUiButton3);
            this.uiPanel1.Controls.Add(this.daUiButton4);
            this.uiPanel1.Controls.Add(this.daUiButton2);
            this.uiPanel1.Controls.Add(this.daUiButton5);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton5, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton2, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton4, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton3, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton15, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton31, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton14, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton1, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton13, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton12, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction2, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton23, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction1, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction3, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction4, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction5, 0);
            // 
            // daUiButton27
            // 
            this.daUiButton27.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton27.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton27.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton27.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton27.FillColor = System.Drawing.Color.Silver;
            this.daUiButton27.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton27.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton27.Location = new System.Drawing.Point(762, 525);
            this.daUiButton27.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton27.Name = "daUiButton27";
            this.daUiButton27.PLC_Enable = true;
            this.daUiButton27.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton27.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton27.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton27.pLCBitselectRealize.BitPattern = false;
            this.daUiButton27.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton27.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton27.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton27.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton27.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton27.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton27.pLCBitselectRealize.OutReverse = false;
            this.daUiButton27.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton27.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton27.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton27.pLCBitselectRealize.ReadWriteAddress = "8220.2";
            this.daUiButton27.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton27.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton27.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton27.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton27.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton27.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton27.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton27.pLCBitselectRealize.Speech = false;
            this.daUiButton27.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton27.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton27.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton27.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton27.pLCBitselectRealize.TextContent_0 = "启动";
            this.daUiButton27.pLCBitselectRealize.TextContent_1 = "启动";
            this.daUiButton27.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton27.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton27.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton27.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton27.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton27.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton27.pLCBitselectRealize.TextState = 0;
            this.daUiButton27.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton27.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton27.pLCBitselectRealize.WriteAddress = "8131.0";
            this.daUiButton27.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton27.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton27.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton27.Size = new System.Drawing.Size(105, 47);
            this.daUiButton27.TabIndex = 60;
            this.daUiButton27.Text = "启动";
            this.daUiButton27.Textalign_0 = "MiddleCenter";
            this.daUiButton27.Textalign_1 = "MiddleCenter";
            this.daUiButton27.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton27.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton27.TextContent_0 = "启动";
            this.daUiButton27.TextContent_1 = "启动";
            this.daUiButton27.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton27.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton26
            // 
            this.daUiButton26.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton26.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton26.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton26.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton26.FillColor = System.Drawing.Color.Silver;
            this.daUiButton26.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton26.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton26.Location = new System.Drawing.Point(631, 525);
            this.daUiButton26.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton26.Name = "daUiButton26";
            this.daUiButton26.PLC_Enable = true;
            this.daUiButton26.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton26.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton26.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton26.pLCBitselectRealize.BitPattern = false;
            this.daUiButton26.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton26.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton26.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton26.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton26.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton26.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton26.pLCBitselectRealize.OutReverse = false;
            this.daUiButton26.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton26.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton26.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton26.pLCBitselectRealize.ReadWriteAddress = "2202.6";
            this.daUiButton26.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton26.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton26.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton26.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton26.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton26.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton26.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton26.pLCBitselectRealize.Speech = false;
            this.daUiButton26.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton26.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton26.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton26.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton26.pLCBitselectRealize.TextContent_0 = "原点回归";
            this.daUiButton26.pLCBitselectRealize.TextContent_1 = "原点回归";
            this.daUiButton26.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton26.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton26.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton26.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton26.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton26.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton26.pLCBitselectRealize.TextState = 0;
            this.daUiButton26.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton26.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton26.pLCBitselectRealize.WriteAddress = "8220.1";
            this.daUiButton26.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton26.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton26.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton26.Size = new System.Drawing.Size(105, 47);
            this.daUiButton26.TabIndex = 59;
            this.daUiButton26.Text = "原点回归";
            this.daUiButton26.Textalign_0 = "MiddleCenter";
            this.daUiButton26.Textalign_1 = "MiddleCenter";
            this.daUiButton26.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton26.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton26.TextContent_0 = "原点回归";
            this.daUiButton26.TextContent_1 = "原点回归";
            this.daUiButton26.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton26.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton25
            // 
            this.daUiButton25.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton25.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton25.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton25.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton25.FillColor = System.Drawing.Color.Silver;
            this.daUiButton25.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton25.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton25.Location = new System.Drawing.Point(499, 525);
            this.daUiButton25.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton25.Name = "daUiButton25";
            this.daUiButton25.PLC_Enable = true;
            this.daUiButton25.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton25.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton25.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton25.pLCBitselectRealize.BitPattern = false;
            this.daUiButton25.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton25.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton25.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton25.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton25.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton25.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton25.pLCBitselectRealize.OutReverse = false;
            this.daUiButton25.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton25.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton25.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton25.pLCBitselectRealize.ReadWriteAddress = "7.1";
            this.daUiButton25.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton25.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton25.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton25.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton25.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton25.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton25.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton25.pLCBitselectRealize.Speech = false;
            this.daUiButton25.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton25.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton25.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton25.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton25.pLCBitselectRealize.TextContent_0 = "复位";
            this.daUiButton25.pLCBitselectRealize.TextContent_1 = "复位";
            this.daUiButton25.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton25.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton25.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton25.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton25.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton25.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton25.pLCBitselectRealize.TextState = 0;
            this.daUiButton25.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton25.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton25.pLCBitselectRealize.WriteAddress = "8131.0";
            this.daUiButton25.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton25.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton25.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton25.Size = new System.Drawing.Size(105, 47);
            this.daUiButton25.TabIndex = 58;
            this.daUiButton25.Text = "复位";
            this.daUiButton25.Textalign_0 = "MiddleCenter";
            this.daUiButton25.Textalign_1 = "MiddleCenter";
            this.daUiButton25.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton25.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton25.TextContent_0 = "复位";
            this.daUiButton25.TextContent_1 = "复位";
            this.daUiButton25.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton25.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton23
            // 
            this.daUiButton23.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton23.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton23.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton23.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton23.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton23.Location = new System.Drawing.Point(681, 71);
            this.daUiButton23.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton23.Name = "daUiButton23";
            this.daUiButton23.PLC_Enable = true;
            this.daUiButton23.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton23.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton23.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton23.pLCBitselectRealize.BitPattern = false;
            this.daUiButton23.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton23.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton23.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton23.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton23.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton23.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton23.pLCBitselectRealize.OutReverse = false;
            this.daUiButton23.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton23.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton23.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton23.pLCBitselectRealize.ReadWriteAddress = "8222.3";
            this.daUiButton23.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton23.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton23.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton23.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton23.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton23.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton23.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton23.pLCBitselectRealize.Speech = false;
            this.daUiButton23.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton23.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton23.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton23.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton23.pLCBitselectRealize.TextContent_0 = "振动盘\n送料";
            this.daUiButton23.pLCBitselectRealize.TextContent_1 = "振动盘\n送料中";
            this.daUiButton23.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton23.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton23.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton23.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton23.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton23.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton23.pLCBitselectRealize.TextState = 0;
            this.daUiButton23.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton23.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton23.pLCBitselectRealize.WriteAddress = "8131.0";
            this.daUiButton23.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton23.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton23.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton23.Size = new System.Drawing.Size(105, 47);
            this.daUiButton23.TabIndex = 51;
            this.daUiButton23.Text = "振动盘\n送料";
            this.daUiButton23.Textalign_0 = "MiddleCenter";
            this.daUiButton23.Textalign_1 = "MiddleCenter";
            this.daUiButton23.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton23.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton23.TextContent_0 = "振动盘\n送料";
            this.daUiButton23.TextContent_1 = "振动盘\n送料中";
            this.daUiButton23.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton23.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton12
            // 
            this.daUiButton12.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton12.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton12.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton12.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton12.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton12.Location = new System.Drawing.Point(515, 167);
            this.daUiButton12.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton12.Name = "daUiButton12";
            this.daUiButton12.PLC_Enable = true;
            this.daUiButton12.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton12.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton12.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton12.pLCBitselectRealize.BitPattern = false;
            this.daUiButton12.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton12.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton12.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton12.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton12.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton12.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton12.pLCBitselectRealize.OutReverse = false;
            this.daUiButton12.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton12.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton12.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton12.pLCBitselectRealize.ReadWriteAddress = "204.5";
            this.daUiButton12.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton12.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton12.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton12.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton12.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton12.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton12.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton12.pLCBitselectRealize.Speech = false;
            this.daUiButton12.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton12.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton12.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton12.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton12.pLCBitselectRealize.TextContent_0 = "  产品\n定位关";
            this.daUiButton12.pLCBitselectRealize.TextContent_1 = "   产品\n定位关中";
            this.daUiButton12.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton12.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton12.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton12.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton12.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton12.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton12.pLCBitselectRealize.TextState = 0;
            this.daUiButton12.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton12.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton12.pLCBitselectRealize.WriteAddress = "6.7";
            this.daUiButton12.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton12.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton12.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton12.Size = new System.Drawing.Size(105, 47);
            this.daUiButton12.TabIndex = 46;
            this.daUiButton12.Text = "  产品\n定位关";
            this.daUiButton12.Textalign_0 = "MiddleCenter";
            this.daUiButton12.Textalign_1 = "MiddleCenter";
            this.daUiButton12.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton12.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton12.TextContent_0 = "  产品\n定位关";
            this.daUiButton12.TextContent_1 = "   产品\n定位关中";
            this.daUiButton12.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton12.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton13
            // 
            this.daUiButton13.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton13.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton13.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton13.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton13.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton13.Location = new System.Drawing.Point(381, 167);
            this.daUiButton13.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton13.Name = "daUiButton13";
            this.daUiButton13.PLC_Enable = true;
            this.daUiButton13.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton13.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton13.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton13.pLCBitselectRealize.BitPattern = false;
            this.daUiButton13.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton13.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton13.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton13.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton13.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton13.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton13.pLCBitselectRealize.OutReverse = false;
            this.daUiButton13.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton13.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton13.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton13.pLCBitselectRealize.ReadWriteAddress = "204.6";
            this.daUiButton13.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton13.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton13.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton13.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton13.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton13.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton13.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton13.pLCBitselectRealize.Speech = false;
            this.daUiButton13.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton13.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton13.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton13.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton13.pLCBitselectRealize.TextContent_0 = "  产品\n定位开";
            this.daUiButton13.pLCBitselectRealize.TextContent_1 = "   产品\n定位开中";
            this.daUiButton13.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton13.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton13.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton13.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton13.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton13.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton13.pLCBitselectRealize.TextState = 0;
            this.daUiButton13.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton13.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton13.pLCBitselectRealize.WriteAddress = "6.6";
            this.daUiButton13.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton13.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton13.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton13.Size = new System.Drawing.Size(105, 47);
            this.daUiButton13.TabIndex = 45;
            this.daUiButton13.Text = "  产品\n定位开";
            this.daUiButton13.Textalign_0 = "MiddleCenter";
            this.daUiButton13.Textalign_1 = "MiddleCenter";
            this.daUiButton13.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton13.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton13.TextContent_0 = "  产品\n定位开";
            this.daUiButton13.TextContent_1 = "   产品\n定位开中";
            this.daUiButton13.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton13.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton14
            // 
            this.daUiButton14.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton14.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton14.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton14.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton14.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton14.Location = new System.Drawing.Point(515, 71);
            this.daUiButton14.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton14.Name = "daUiButton14";
            this.daUiButton14.PLC_Enable = true;
            this.daUiButton14.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton14.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton14.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton14.pLCBitselectRealize.BitPattern = false;
            this.daUiButton14.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton14.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton14.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton14.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton14.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton14.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton14.pLCBitselectRealize.OutReverse = false;
            this.daUiButton14.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton14.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton14.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton14.pLCBitselectRealize.ReadWriteAddress = "204.1";
            this.daUiButton14.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton14.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton14.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton14.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton14.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton14.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton14.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton14.pLCBitselectRealize.Speech = false;
            this.daUiButton14.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton14.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton14.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton14.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton14.pLCBitselectRealize.TextContent_0 = "   产品\n阻挡下降";
            this.daUiButton14.pLCBitselectRealize.TextContent_1 = "    产品\n阻挡下降中 ";
            this.daUiButton14.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton14.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton14.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton14.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton14.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton14.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton14.pLCBitselectRealize.TextState = 0;
            this.daUiButton14.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton14.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton14.pLCBitselectRealize.WriteAddress = "8223.0";
            this.daUiButton14.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton14.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton14.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton14.Size = new System.Drawing.Size(105, 47);
            this.daUiButton14.TabIndex = 44;
            this.daUiButton14.Text = "   产品\n阻挡下降";
            this.daUiButton14.Textalign_0 = "MiddleCenter";
            this.daUiButton14.Textalign_1 = "MiddleCenter";
            this.daUiButton14.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton14.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton14.TextContent_0 = "   产品\n阻挡下降";
            this.daUiButton14.TextContent_1 = "    产品\n阻挡下降中 ";
            this.daUiButton14.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton14.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton15
            // 
            this.daUiButton15.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton15.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton15.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton15.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton15.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton15.Location = new System.Drawing.Point(381, 71);
            this.daUiButton15.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton15.Name = "daUiButton15";
            this.daUiButton15.PLC_Enable = true;
            this.daUiButton15.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton15.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton15.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton15.pLCBitselectRealize.BitPattern = false;
            this.daUiButton15.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton15.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton15.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton15.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton15.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton15.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton15.pLCBitselectRealize.OutReverse = false;
            this.daUiButton15.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton15.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton15.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton15.pLCBitselectRealize.ReadWriteAddress = "205.1";
            this.daUiButton15.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton15.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton15.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton15.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton15.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton15.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton15.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton15.pLCBitselectRealize.Speech = false;
            this.daUiButton15.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton15.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton15.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton15.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton15.pLCBitselectRealize.TextContent_0 = "   产品\n阻挡上升";
            this.daUiButton15.pLCBitselectRealize.TextContent_1 = "    产品\n阻挡上升中";
            this.daUiButton15.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton15.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton15.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton15.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton15.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton15.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton15.pLCBitselectRealize.TextState = 0;
            this.daUiButton15.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton15.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton15.pLCBitselectRealize.WriteAddress = "8222.7";
            this.daUiButton15.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton15.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton15.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton15.Size = new System.Drawing.Size(105, 47);
            this.daUiButton15.TabIndex = 43;
            this.daUiButton15.Text = "   产品\n阻挡上升";
            this.daUiButton15.Textalign_0 = "MiddleCenter";
            this.daUiButton15.Textalign_1 = "MiddleCenter";
            this.daUiButton15.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton15.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton15.TextContent_0 = "   产品\n阻挡上升";
            this.daUiButton15.TextContent_1 = "    产品\n阻挡上升中";
            this.daUiButton15.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton15.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton4
            // 
            this.daUiButton4.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton4.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton4.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton4.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton4.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.Location = new System.Drawing.Point(211, 262);
            this.daUiButton4.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton4.Name = "daUiButton4";
            this.daUiButton4.PLC_Enable = true;
            this.daUiButton4.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton4.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton4.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton4.pLCBitselectRealize.BitPattern = false;
            this.daUiButton4.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton4.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton4.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton4.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton4.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton4.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton4.pLCBitselectRealize.OutReverse = false;
            this.daUiButton4.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton4.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton4.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton4.pLCBitselectRealize.ReadWriteAddress = "204.3";
            this.daUiButton4.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton4.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton4.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton4.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton4.pLCBitselectRealize.Speech = false;
            this.daUiButton4.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton4.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton4.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton4.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton4.pLCBitselectRealize.TextContent_0 = "  产品B\n旋转退回";
            this.daUiButton4.pLCBitselectRealize.TextContent_1 = "   产品B\n旋转退回中";
            this.daUiButton4.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton4.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton4.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton4.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton4.pLCBitselectRealize.TextState = 0;
            this.daUiButton4.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton4.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton4.pLCBitselectRealize.WriteAddress = "3.2";
            this.daUiButton4.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton4.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton4.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton4.Size = new System.Drawing.Size(105, 47);
            this.daUiButton4.TabIndex = 40;
            this.daUiButton4.Text = "  产品B\n旋转退回";
            this.daUiButton4.Textalign_0 = "MiddleCenter";
            this.daUiButton4.Textalign_1 = "MiddleCenter";
            this.daUiButton4.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton4.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton4.TextContent_0 = "  产品B\n旋转退回";
            this.daUiButton4.TextContent_1 = "   产品B\n旋转退回中";
            this.daUiButton4.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton5
            // 
            this.daUiButton5.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton5.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton5.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton5.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton5.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.Location = new System.Drawing.Point(77, 262);
            this.daUiButton5.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton5.Name = "daUiButton5";
            this.daUiButton5.PLC_Enable = true;
            this.daUiButton5.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton5.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton5.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton5.pLCBitselectRealize.BitPattern = false;
            this.daUiButton5.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton5.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton5.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton5.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton5.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton5.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton5.pLCBitselectRealize.OutReverse = false;
            this.daUiButton5.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton5.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton5.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton5.pLCBitselectRealize.ReadWriteAddress = "205.3";
            this.daUiButton5.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton5.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton5.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton5.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton5.pLCBitselectRealize.Speech = false;
            this.daUiButton5.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton5.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton5.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton5.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton5.pLCBitselectRealize.TextContent_0 = "  产品B\n旋转推出";
            this.daUiButton5.pLCBitselectRealize.TextContent_1 = "   产品B\n旋转推出中";
            this.daUiButton5.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton5.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton5.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton5.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton5.pLCBitselectRealize.TextState = 0;
            this.daUiButton5.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton5.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton5.pLCBitselectRealize.WriteAddress = "3.3";
            this.daUiButton5.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton5.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton5.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton5.Size = new System.Drawing.Size(105, 47);
            this.daUiButton5.TabIndex = 39;
            this.daUiButton5.Text = "  产品B\n旋转推出";
            this.daUiButton5.Textalign_0 = "MiddleCenter";
            this.daUiButton5.Textalign_1 = "MiddleCenter";
            this.daUiButton5.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton5.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton5.TextContent_0 = "  产品B\n旋转推出";
            this.daUiButton5.TextContent_1 = "   产品B\n旋转推出中";
            this.daUiButton5.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton2
            // 
            this.daUiButton2.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton2.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton2.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton2.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.Location = new System.Drawing.Point(211, 167);
            this.daUiButton2.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton2.Name = "daUiButton2";
            this.daUiButton2.PLC_Enable = true;
            this.daUiButton2.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton2.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton2.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton2.pLCBitselectRealize.BitPattern = false;
            this.daUiButton2.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton2.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton2.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton2.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton2.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton2.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton2.pLCBitselectRealize.OutReverse = false;
            this.daUiButton2.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton2.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton2.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton2.pLCBitselectRealize.ReadWriteAddress = "203.5";
            this.daUiButton2.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton2.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton2.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton2.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton2.pLCBitselectRealize.Speech = false;
            this.daUiButton2.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton2.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton2.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton2.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton2.pLCBitselectRealize.TextContent_0 = "   分料\n移栽推出";
            this.daUiButton2.pLCBitselectRealize.TextContent_1 = "    分料\n移栽推出中";
            this.daUiButton2.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton2.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton2.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton2.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton2.pLCBitselectRealize.TextState = 0;
            this.daUiButton2.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton2.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton2.pLCBitselectRealize.WriteAddress = "8222.0";
            this.daUiButton2.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton2.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton2.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton2.Size = new System.Drawing.Size(105, 47);
            this.daUiButton2.TabIndex = 38;
            this.daUiButton2.Text = "   分料\n移栽推出";
            this.daUiButton2.Textalign_0 = "MiddleCenter";
            this.daUiButton2.Textalign_1 = "MiddleCenter";
            this.daUiButton2.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton2.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton2.TextContent_0 = "   分料\n移栽推出";
            this.daUiButton2.TextContent_1 = "    分料\n移栽推出中";
            this.daUiButton2.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton3
            // 
            this.daUiButton3.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton3.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton3.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton3.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.Location = new System.Drawing.Point(77, 167);
            this.daUiButton3.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton3.Name = "daUiButton3";
            this.daUiButton3.PLC_Enable = true;
            this.daUiButton3.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton3.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton3.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton3.pLCBitselectRealize.BitPattern = false;
            this.daUiButton3.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton3.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton3.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton3.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton3.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton3.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton3.pLCBitselectRealize.OutReverse = false;
            this.daUiButton3.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton3.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton3.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton3.pLCBitselectRealize.ReadWriteAddress = "204.5";
            this.daUiButton3.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton3.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton3.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton3.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton3.pLCBitselectRealize.Speech = false;
            this.daUiButton3.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton3.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton3.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton3.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton3.pLCBitselectRealize.TextContent_0 = "   分料\n移栽退回";
            this.daUiButton3.pLCBitselectRealize.TextContent_1 = "    分料\n移栽退回中";
            this.daUiButton3.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton3.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton3.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton3.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton3.pLCBitselectRealize.TextState = 0;
            this.daUiButton3.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton3.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton3.pLCBitselectRealize.WriteAddress = "8221.7";
            this.daUiButton3.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton3.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton3.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton3.Size = new System.Drawing.Size(105, 47);
            this.daUiButton3.TabIndex = 37;
            this.daUiButton3.Text = "   分料\n移栽退回";
            this.daUiButton3.Textalign_0 = "MiddleCenter";
            this.daUiButton3.Textalign_1 = "MiddleCenter";
            this.daUiButton3.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton3.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton3.TextContent_0 = "   分料\n移栽退回";
            this.daUiButton3.TextContent_1 = "    分料\n移栽退回中";
            this.daUiButton3.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton1
            // 
            this.daUiButton1.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton1.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton1.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton1.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.Location = new System.Drawing.Point(211, 71);
            this.daUiButton1.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton1.Name = "daUiButton1";
            this.daUiButton1.PLC_Enable = true;
            this.daUiButton1.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton1.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton1.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton1.pLCBitselectRealize.BitPattern = false;
            this.daUiButton1.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton1.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton1.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton1.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton1.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton1.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton1.pLCBitselectRealize.OutReverse = false;
            this.daUiButton1.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton1.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton1.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton1.pLCBitselectRealize.ReadWriteAddress = "205.2";
            this.daUiButton1.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton1.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton1.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton1.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton1.pLCBitselectRealize.Speech = false;
            this.daUiButton1.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton1.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton1.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton1.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton1.pLCBitselectRealize.TextContent_0 = "   移栽\n升降下降";
            this.daUiButton1.pLCBitselectRealize.TextContent_1 = "   移栽\n升降下降中";
            this.daUiButton1.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton1.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton1.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton1.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton1.pLCBitselectRealize.TextState = 0;
            this.daUiButton1.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton1.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton1.pLCBitselectRealize.WriteAddress = "8220.4";
            this.daUiButton1.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton1.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton1.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton1.Size = new System.Drawing.Size(105, 47);
            this.daUiButton1.TabIndex = 36;
            this.daUiButton1.Text = "   移栽\n升降下降";
            this.daUiButton1.Textalign_0 = "MiddleCenter";
            this.daUiButton1.Textalign_1 = "MiddleCenter";
            this.daUiButton1.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton1.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton1.TextContent_0 = "   移栽\n升降下降";
            this.daUiButton1.TextContent_1 = "   移栽\n升降下降中";
            this.daUiButton1.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton31
            // 
            this.daUiButton31.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton31.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton31.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton31.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton31.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.Location = new System.Drawing.Point(77, 71);
            this.daUiButton31.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton31.Name = "daUiButton31";
            this.daUiButton31.PLC_Enable = true;
            this.daUiButton31.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton31.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton31.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton31.pLCBitselectRealize.BitPattern = false;
            this.daUiButton31.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton31.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton31.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton31.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton31.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton31.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton31.pLCBitselectRealize.OutReverse = false;
            this.daUiButton31.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton31.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton31.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton31.pLCBitselectRealize.ReadWriteAddress = "204.2";
            this.daUiButton31.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton31.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton31.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton31.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton31.pLCBitselectRealize.Speech = false;
            this.daUiButton31.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton31.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton31.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton31.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton31.pLCBitselectRealize.TextContent_0 = "   移栽\n升降上升";
            this.daUiButton31.pLCBitselectRealize.TextContent_1 = "    移栽\n升降上升中";
            this.daUiButton31.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton31.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton31.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton31.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton31.pLCBitselectRealize.TextState = 0;
            this.daUiButton31.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton31.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton31.pLCBitselectRealize.WriteAddress = "8220.3";
            this.daUiButton31.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton31.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton31.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton31.Size = new System.Drawing.Size(105, 47);
            this.daUiButton31.TabIndex = 35;
            this.daUiButton31.Text = "   移栽\n升降上升";
            this.daUiButton31.Textalign_0 = "MiddleCenter";
            this.daUiButton31.Textalign_1 = "MiddleCenter";
            this.daUiButton31.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton31.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton31.TextContent_0 = "   移栽\n升降上升";
            this.daUiButton31.TextContent_1 = "    移栽\n升降上升中";
            this.daUiButton31.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // ZDP1手动界面
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(897, 679);
            this.Controls.Add(this.daUiButton27);
            this.Controls.Add(this.daUiButton26);
            this.Controls.Add(this.daUiButton25);
            this.Name = "ZDP1手动界面";
            this.Text = "ZDP1手动界面";
            this.Controls.SetChildIndex(this.uiPanel1, 0);
            this.Controls.SetChildIndex(this.daUiButton25, 0);
            this.Controls.SetChildIndex(this.daUiButton26, 0);
            this.Controls.SetChildIndex(this.daUiButton27, 0);
            this.uiPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private 基础控件.DAUiButton daUiButton27;
        private 基础控件.DAUiButton daUiButton26;
        private 基础控件.DAUiButton daUiButton25;
        private 基础控件.DAUiButton daUiButton23;
        private 基础控件.DAUiButton daUiButton12;
        private 基础控件.DAUiButton daUiButton13;
        private 基础控件.DAUiButton daUiButton14;
        private 基础控件.DAUiButton daUiButton15;
        private 基础控件.DAUiButton daUiButton4;
        private 基础控件.DAUiButton daUiButton5;
        private 基础控件.DAUiButton daUiButton2;
        private 基础控件.DAUiButton daUiButton3;
        private 基础控件.DAUiButton daUiButton1;
        private 基础控件.DAUiButton daUiButton31;
    }
}