
namespace PLC通讯基础控件项目.模板与控制界面.一区手动界面
{
    partial class ZWJ手动界面
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.daUiButton18 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton19 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton20 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton21 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton22 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton23 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton2 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton3 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton1 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton31 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton4 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton5 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton6 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton7 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.uiPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // uiPanel1
            // 
            this.uiPanel1.Controls.Add(this.daUiButton6);
            this.uiPanel1.Controls.Add(this.daUiButton7);
            this.uiPanel1.Controls.Add(this.daUiButton4);
            this.uiPanel1.Controls.Add(this.daUiButton5);
            this.uiPanel1.Controls.Add(this.daUiButton18);
            this.uiPanel1.Controls.Add(this.daUiButton19);
            this.uiPanel1.Controls.Add(this.daUiButton20);
            this.uiPanel1.Controls.Add(this.daUiButton21);
            this.uiPanel1.Controls.Add(this.daUiButton22);
            this.uiPanel1.Controls.Add(this.daUiButton23);
            this.uiPanel1.Controls.Add(this.daUiButton2);
            this.uiPanel1.Controls.Add(this.daUiButton3);
            this.uiPanel1.Controls.Add(this.daUiButton31);
            this.uiPanel1.Controls.Add(this.daUiButton1);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton1, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton31, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton3, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton2, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction2, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton23, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction1, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton22, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction3, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton21, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction4, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton20, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction5, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton19, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton18, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton5, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton4, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton7, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton6, 0);
            // 
            // daUiButton18
            // 
            this.daUiButton18.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton18.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton18.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton18.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton18.FillColor = System.Drawing.Color.Silver;
            this.daUiButton18.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton18.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton18.Location = new System.Drawing.Point(242, 452);
            this.daUiButton18.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton18.Name = "daUiButton18";
            this.daUiButton18.PLC_Enable = true;
            this.daUiButton18.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton18.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton18.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton18.pLCBitselectRealize.BitPattern = false;
            this.daUiButton18.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton18.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton18.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton18.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton18.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton18.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton18.pLCBitselectRealize.OutReverse = false;
            this.daUiButton18.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton18.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton18.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton18.pLCBitselectRealize.ReadWriteAddress = "9022.0";
            this.daUiButton18.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton18.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton18.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton18.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton18.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton18.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton18.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton18.pLCBitselectRealize.Speech = false;
            this.daUiButton18.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton18.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton18.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton18.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton18.pLCBitselectRealize.TextContent_0 = "折弯机\n取件完成";
            this.daUiButton18.pLCBitselectRealize.TextContent_1 = "折弯机\n取件完成";
            this.daUiButton18.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton18.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton18.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton18.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton18.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton18.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton18.pLCBitselectRealize.TextState = 0;
            this.daUiButton18.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton18.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton18.pLCBitselectRealize.WriteAddress = "8131.0";
            this.daUiButton18.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton18.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton18.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton18.Size = new System.Drawing.Size(105, 47);
            this.daUiButton18.TabIndex = 66;
            this.daUiButton18.Text = "折弯机\n取件完成";
            this.daUiButton18.Textalign_0 = "MiddleCenter";
            this.daUiButton18.Textalign_1 = "MiddleCenter";
            this.daUiButton18.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton18.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton18.TextContent_0 = "折弯机\n取件完成";
            this.daUiButton18.TextContent_1 = "折弯机\n取件完成";
            this.daUiButton18.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton18.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton19
            // 
            this.daUiButton19.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton19.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton19.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton19.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton19.FillColor = System.Drawing.Color.Silver;
            this.daUiButton19.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton19.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.Location = new System.Drawing.Point(108, 452);
            this.daUiButton19.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton19.Name = "daUiButton19";
            this.daUiButton19.PLC_Enable = true;
            this.daUiButton19.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton19.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton19.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton19.pLCBitselectRealize.BitPattern = false;
            this.daUiButton19.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton19.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton19.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton19.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton19.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton19.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton19.pLCBitselectRealize.OutReverse = false;
            this.daUiButton19.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton19.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton19.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton19.pLCBitselectRealize.ReadWriteAddress = "9021.3";
            this.daUiButton19.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton19.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton19.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton19.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton19.pLCBitselectRealize.Speech = false;
            this.daUiButton19.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton19.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton19.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton19.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton19.pLCBitselectRealize.TextContent_0 = "折弯机\n启动";
            this.daUiButton19.pLCBitselectRealize.TextContent_1 = "折弯机\n启动中";
            this.daUiButton19.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton19.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton19.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton19.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton19.pLCBitselectRealize.TextState = 0;
            this.daUiButton19.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton19.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton19.pLCBitselectRealize.WriteAddress = "8131.0";
            this.daUiButton19.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton19.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton19.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton19.Size = new System.Drawing.Size(105, 47);
            this.daUiButton19.TabIndex = 65;
            this.daUiButton19.Text = "折弯机\n启动";
            this.daUiButton19.Textalign_0 = "MiddleCenter";
            this.daUiButton19.Textalign_1 = "MiddleCenter";
            this.daUiButton19.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton19.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton19.TextContent_0 = "折弯机\n启动";
            this.daUiButton19.TextContent_1 = "折弯机\n启动中";
            this.daUiButton19.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton20
            // 
            this.daUiButton20.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton20.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton20.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton20.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton20.FillColor = System.Drawing.Color.Silver;
            this.daUiButton20.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton20.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton20.Location = new System.Drawing.Point(242, 362);
            this.daUiButton20.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton20.Name = "daUiButton20";
            this.daUiButton20.PLC_Enable = true;
            this.daUiButton20.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton20.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton20.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton20.pLCBitselectRealize.BitPattern = false;
            this.daUiButton20.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton20.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton20.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton20.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton20.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton20.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton20.pLCBitselectRealize.OutReverse = false;
            this.daUiButton20.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton20.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton20.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton20.pLCBitselectRealize.ReadWriteAddress = "203.0";
            this.daUiButton20.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton20.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton20.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton20.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton20.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton20.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton20.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton20.pLCBitselectRealize.Speech = false;
            this.daUiButton20.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton20.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton20.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton20.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton20.pLCBitselectRealize.TextContent_0 = "  右折\n平上升";
            this.daUiButton20.pLCBitselectRealize.TextContent_1 = "   右折\n平上升中";
            this.daUiButton20.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton20.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton20.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton20.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton20.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton20.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton20.pLCBitselectRealize.TextState = 0;
            this.daUiButton20.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton20.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton20.pLCBitselectRealize.WriteAddress = "9020.2";
            this.daUiButton20.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton20.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton20.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton20.Size = new System.Drawing.Size(105, 47);
            this.daUiButton20.TabIndex = 64;
            this.daUiButton20.Text = "  右折\n平上升";
            this.daUiButton20.Textalign_0 = "MiddleCenter";
            this.daUiButton20.Textalign_1 = "MiddleCenter";
            this.daUiButton20.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton20.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton20.TextContent_0 = "  右折\n平上升";
            this.daUiButton20.TextContent_1 = "   右折\n平上升中";
            this.daUiButton20.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton20.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton21
            // 
            this.daUiButton21.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton21.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton21.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton21.FillColor = System.Drawing.Color.Silver;
            this.daUiButton21.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton21.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton21.Location = new System.Drawing.Point(108, 362);
            this.daUiButton21.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton21.Name = "daUiButton21";
            this.daUiButton21.PLC_Enable = true;
            this.daUiButton21.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton21.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton21.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton21.pLCBitselectRealize.BitPattern = false;
            this.daUiButton21.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton21.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton21.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton21.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton21.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton21.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton21.pLCBitselectRealize.OutReverse = false;
            this.daUiButton21.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton21.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton21.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton21.pLCBitselectRealize.ReadWriteAddress = "203.1";
            this.daUiButton21.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton21.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton21.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton21.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton21.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton21.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton21.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton21.pLCBitselectRealize.Speech = false;
            this.daUiButton21.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton21.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton21.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton21.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton21.pLCBitselectRealize.TextContent_0 = "  右折\n平下降";
            this.daUiButton21.pLCBitselectRealize.TextContent_1 = "   右折\n平下降中";
            this.daUiButton21.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton21.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton21.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton21.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton21.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton21.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton21.pLCBitselectRealize.TextState = 0;
            this.daUiButton21.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton21.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton21.pLCBitselectRealize.WriteAddress = "9020.3";
            this.daUiButton21.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton21.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton21.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton21.Size = new System.Drawing.Size(105, 47);
            this.daUiButton21.TabIndex = 63;
            this.daUiButton21.Text = "  右折\n平下降";
            this.daUiButton21.Textalign_0 = "MiddleCenter";
            this.daUiButton21.Textalign_1 = "MiddleCenter";
            this.daUiButton21.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton21.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton21.TextContent_0 = "  右折\n平下降";
            this.daUiButton21.TextContent_1 = "   右折\n平下降中";
            this.daUiButton21.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton21.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton22
            // 
            this.daUiButton22.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton22.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton22.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton22.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton22.FillColor = System.Drawing.Color.Silver;
            this.daUiButton22.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton22.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton22.Location = new System.Drawing.Point(242, 266);
            this.daUiButton22.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton22.Name = "daUiButton22";
            this.daUiButton22.PLC_Enable = true;
            this.daUiButton22.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton22.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton22.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton22.pLCBitselectRealize.BitPattern = false;
            this.daUiButton22.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton22.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton22.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton22.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton22.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton22.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton22.pLCBitselectRealize.OutReverse = false;
            this.daUiButton22.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton22.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton22.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton22.pLCBitselectRealize.ReadWriteAddress = "202.6";
            this.daUiButton22.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton22.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton22.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton22.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton22.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton22.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton22.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton22.pLCBitselectRealize.Speech = false;
            this.daUiButton22.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton22.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton22.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton22.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton22.pLCBitselectRealize.TextContent_0 = "  左折\n平上升";
            this.daUiButton22.pLCBitselectRealize.TextContent_1 = "   左折\n平上升中";
            this.daUiButton22.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton22.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton22.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton22.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton22.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton22.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton22.pLCBitselectRealize.TextState = 0;
            this.daUiButton22.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton22.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton22.pLCBitselectRealize.WriteAddress = "9020.0";
            this.daUiButton22.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton22.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton22.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton22.Size = new System.Drawing.Size(105, 47);
            this.daUiButton22.TabIndex = 62;
            this.daUiButton22.Text = "  左折\n平上升";
            this.daUiButton22.Textalign_0 = "MiddleCenter";
            this.daUiButton22.Textalign_1 = "MiddleCenter";
            this.daUiButton22.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton22.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton22.TextContent_0 = "  左折\n平上升";
            this.daUiButton22.TextContent_1 = "   左折\n平上升中";
            this.daUiButton22.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton22.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton23
            // 
            this.daUiButton23.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton23.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton23.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton23.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton23.FillColor = System.Drawing.Color.Silver;
            this.daUiButton23.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton23.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton23.Location = new System.Drawing.Point(108, 266);
            this.daUiButton23.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton23.Name = "daUiButton23";
            this.daUiButton23.PLC_Enable = true;
            this.daUiButton23.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton23.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton23.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton23.pLCBitselectRealize.BitPattern = false;
            this.daUiButton23.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton23.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton23.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton23.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton23.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton23.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton23.pLCBitselectRealize.OutReverse = false;
            this.daUiButton23.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton23.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton23.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton23.pLCBitselectRealize.ReadWriteAddress = "202.7";
            this.daUiButton23.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton23.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton23.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton23.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton23.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton23.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton23.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton23.pLCBitselectRealize.Speech = false;
            this.daUiButton23.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton23.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton23.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton23.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton23.pLCBitselectRealize.TextContent_0 = "  左折\n平下降";
            this.daUiButton23.pLCBitselectRealize.TextContent_1 = "   左折\n平下降中";
            this.daUiButton23.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton23.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton23.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton23.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton23.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton23.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton23.pLCBitselectRealize.TextState = 0;
            this.daUiButton23.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton23.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton23.pLCBitselectRealize.WriteAddress = "9020.1";
            this.daUiButton23.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton23.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton23.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton23.Size = new System.Drawing.Size(105, 47);
            this.daUiButton23.TabIndex = 61;
            this.daUiButton23.Text = "  左折\n平下降";
            this.daUiButton23.Textalign_0 = "MiddleCenter";
            this.daUiButton23.Textalign_1 = "MiddleCenter";
            this.daUiButton23.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton23.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton23.TextContent_0 = "  左折\n平下降";
            this.daUiButton23.TextContent_1 = "   左折\n平下降中";
            this.daUiButton23.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton23.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton2
            // 
            this.daUiButton2.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton2.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton2.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton2.FillColor = System.Drawing.Color.Silver;
            this.daUiButton2.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton2.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.Location = new System.Drawing.Point(242, 171);
            this.daUiButton2.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton2.Name = "daUiButton2";
            this.daUiButton2.PLC_Enable = true;
            this.daUiButton2.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton2.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton2.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton2.pLCBitselectRealize.BitPattern = false;
            this.daUiButton2.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton2.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton2.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton2.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton2.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton2.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton2.pLCBitselectRealize.OutReverse = false;
            this.daUiButton2.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton2.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton2.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton2.pLCBitselectRealize.ReadWriteAddress = "202.3";
            this.daUiButton2.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton2.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton2.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton2.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton2.pLCBitselectRealize.Speech = false;
            this.daUiButton2.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton2.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton2.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton2.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton2.pLCBitselectRealize.TextContent_0 = "折弯关";
            this.daUiButton2.pLCBitselectRealize.TextContent_1 = "折弯关中";
            this.daUiButton2.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton2.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton2.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton2.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton2.pLCBitselectRealize.TextState = 0;
            this.daUiButton2.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton2.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton2.pLCBitselectRealize.WriteAddress = "9020.7";
            this.daUiButton2.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton2.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton2.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton2.Size = new System.Drawing.Size(105, 47);
            this.daUiButton2.TabIndex = 60;
            this.daUiButton2.Text = "折弯关";
            this.daUiButton2.Textalign_0 = "MiddleCenter";
            this.daUiButton2.Textalign_1 = "MiddleCenter";
            this.daUiButton2.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton2.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton2.TextContent_0 = "折弯关";
            this.daUiButton2.TextContent_1 = "折弯关中";
            this.daUiButton2.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton3
            // 
            this.daUiButton3.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton3.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton3.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton3.FillColor = System.Drawing.Color.Silver;
            this.daUiButton3.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton3.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.Location = new System.Drawing.Point(108, 171);
            this.daUiButton3.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton3.Name = "daUiButton3";
            this.daUiButton3.PLC_Enable = true;
            this.daUiButton3.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton3.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton3.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton3.pLCBitselectRealize.BitPattern = false;
            this.daUiButton3.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton3.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton3.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton3.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton3.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton3.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton3.pLCBitselectRealize.OutReverse = false;
            this.daUiButton3.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton3.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton3.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton3.pLCBitselectRealize.ReadWriteAddress = "202.2";
            this.daUiButton3.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton3.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton3.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton3.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton3.pLCBitselectRealize.Speech = false;
            this.daUiButton3.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton3.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton3.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton3.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton3.pLCBitselectRealize.TextContent_0 = "折弯开";
            this.daUiButton3.pLCBitselectRealize.TextContent_1 = "折弯开中";
            this.daUiButton3.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton3.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton3.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton3.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton3.pLCBitselectRealize.TextState = 0;
            this.daUiButton3.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton3.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton3.pLCBitselectRealize.WriteAddress = "9020.6";
            this.daUiButton3.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton3.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton3.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton3.Size = new System.Drawing.Size(105, 47);
            this.daUiButton3.TabIndex = 59;
            this.daUiButton3.Text = "折弯开";
            this.daUiButton3.Textalign_0 = "MiddleCenter";
            this.daUiButton3.Textalign_1 = "MiddleCenter";
            this.daUiButton3.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton3.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton3.TextContent_0 = "折弯开";
            this.daUiButton3.TextContent_1 = "折弯开中";
            this.daUiButton3.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton1
            // 
            this.daUiButton1.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton1.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton1.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton1.FillColor = System.Drawing.Color.Silver;
            this.daUiButton1.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton1.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.Location = new System.Drawing.Point(242, 75);
            this.daUiButton1.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton1.Name = "daUiButton1";
            this.daUiButton1.PLC_Enable = true;
            this.daUiButton1.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton1.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton1.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton1.pLCBitselectRealize.BitPattern = false;
            this.daUiButton1.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton1.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton1.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton1.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton1.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton1.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton1.pLCBitselectRealize.OutReverse = false;
            this.daUiButton1.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton1.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton1.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton1.pLCBitselectRealize.ReadWriteAddress = "202.1";
            this.daUiButton1.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton1.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton1.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton1.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton1.pLCBitselectRealize.Speech = false;
            this.daUiButton1.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton1.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton1.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton1.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton1.pLCBitselectRealize.TextContent_0 = "压紧上升";
            this.daUiButton1.pLCBitselectRealize.TextContent_1 = "压紧上升中";
            this.daUiButton1.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton1.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton1.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton1.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton1.pLCBitselectRealize.TextState = 0;
            this.daUiButton1.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton1.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton1.pLCBitselectRealize.WriteAddress = "9020.5";
            this.daUiButton1.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton1.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton1.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton1.Size = new System.Drawing.Size(105, 47);
            this.daUiButton1.TabIndex = 58;
            this.daUiButton1.Text = "压紧上升";
            this.daUiButton1.Textalign_0 = "MiddleCenter";
            this.daUiButton1.Textalign_1 = "MiddleCenter";
            this.daUiButton1.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton1.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton1.TextContent_0 = "压紧上升";
            this.daUiButton1.TextContent_1 = "压紧上升中";
            this.daUiButton1.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton31
            // 
            this.daUiButton31.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton31.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton31.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton31.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton31.FillColor = System.Drawing.Color.Silver;
            this.daUiButton31.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton31.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.Location = new System.Drawing.Point(108, 75);
            this.daUiButton31.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton31.Name = "daUiButton31";
            this.daUiButton31.PLC_Enable = true;
            this.daUiButton31.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton31.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton31.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton31.pLCBitselectRealize.BitPattern = false;
            this.daUiButton31.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton31.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton31.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton31.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton31.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton31.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton31.pLCBitselectRealize.OutReverse = false;
            this.daUiButton31.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton31.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton31.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton31.pLCBitselectRealize.ReadWriteAddress = "202.0";
            this.daUiButton31.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton31.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton31.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton31.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton31.pLCBitselectRealize.Speech = false;
            this.daUiButton31.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton31.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton31.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton31.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton31.pLCBitselectRealize.TextContent_0 = "压紧下压";
            this.daUiButton31.pLCBitselectRealize.TextContent_1 = "压紧下压中";
            this.daUiButton31.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton31.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton31.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton31.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton31.pLCBitselectRealize.TextState = 0;
            this.daUiButton31.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton31.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton31.pLCBitselectRealize.WriteAddress = "9020.4";
            this.daUiButton31.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton31.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton31.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton31.Size = new System.Drawing.Size(105, 47);
            this.daUiButton31.TabIndex = 57;
            this.daUiButton31.Text = "压紧下压";
            this.daUiButton31.Textalign_0 = "MiddleCenter";
            this.daUiButton31.Textalign_1 = "MiddleCenter";
            this.daUiButton31.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton31.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton31.TextContent_0 = "压紧下压";
            this.daUiButton31.TextContent_1 = "压紧下压中";
            this.daUiButton31.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton4
            // 
            this.daUiButton4.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton4.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton4.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton4.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton4.FillColor = System.Drawing.Color.Silver;
            this.daUiButton4.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton4.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.Location = new System.Drawing.Point(517, 75);
            this.daUiButton4.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton4.Name = "daUiButton4";
            this.daUiButton4.PLC_Enable = true;
            this.daUiButton4.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton4.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton4.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton4.pLCBitselectRealize.BitPattern = false;
            this.daUiButton4.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton4.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton4.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton4.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton4.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton4.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton4.pLCBitselectRealize.OutReverse = false;
            this.daUiButton4.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton4.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton4.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton4.pLCBitselectRealize.ReadWriteAddress = "203.2";
            this.daUiButton4.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton4.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton4.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton4.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton4.pLCBitselectRealize.Speech = false;
            this.daUiButton4.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton4.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton4.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton4.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton4.pLCBitselectRealize.TextContent_0 = "  折弯\n顶针脱料";
            this.daUiButton4.pLCBitselectRealize.TextContent_1 = "   折弯\n顶针脱料中";
            this.daUiButton4.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton4.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton4.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton4.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton4.pLCBitselectRealize.TextState = 0;
            this.daUiButton4.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton4.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton4.pLCBitselectRealize.WriteAddress = "9021.0";
            this.daUiButton4.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton4.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton4.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton4.Size = new System.Drawing.Size(105, 47);
            this.daUiButton4.TabIndex = 67;
            this.daUiButton4.Text = "  折弯\n顶针脱料";
            this.daUiButton4.Textalign_0 = "MiddleCenter";
            this.daUiButton4.Textalign_1 = "MiddleCenter";
            this.daUiButton4.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton4.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton4.TextContent_0 = "  折弯\n顶针脱料";
            this.daUiButton4.TextContent_1 = "   折弯\n顶针脱料中";
            this.daUiButton4.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton5
            // 
            this.daUiButton5.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton5.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton5.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton5.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton5.FillColor = System.Drawing.Color.Silver;
            this.daUiButton5.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton5.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.Location = new System.Drawing.Point(651, 75);
            this.daUiButton5.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton5.Name = "daUiButton5";
            this.daUiButton5.PLC_Enable = true;
            this.daUiButton5.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton5.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton5.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton5.pLCBitselectRealize.BitPattern = false;
            this.daUiButton5.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton5.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton5.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton5.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton5.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton5.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton5.pLCBitselectRealize.OutReverse = false;
            this.daUiButton5.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton5.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton5.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton5.pLCBitselectRealize.ReadWriteAddress = "203.3";
            this.daUiButton5.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton5.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton5.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton5.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton5.pLCBitselectRealize.Speech = false;
            this.daUiButton5.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton5.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton5.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton5.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton5.pLCBitselectRealize.TextContent_0 = "   折弯\n顶针原点";
            this.daUiButton5.pLCBitselectRealize.TextContent_1 = "    折弯\n顶针原点中";
            this.daUiButton5.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton5.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton5.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton5.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton5.pLCBitselectRealize.TextState = 0;
            this.daUiButton5.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton5.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton5.pLCBitselectRealize.WriteAddress = "9021.1";
            this.daUiButton5.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton5.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton5.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton5.Size = new System.Drawing.Size(105, 47);
            this.daUiButton5.TabIndex = 68;
            this.daUiButton5.Text = "   折弯\n顶针原点";
            this.daUiButton5.Textalign_0 = "MiddleCenter";
            this.daUiButton5.Textalign_1 = "MiddleCenter";
            this.daUiButton5.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton5.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton5.TextContent_0 = "   折弯\n顶针原点";
            this.daUiButton5.TextContent_1 = "    折弯\n顶针原点中";
            this.daUiButton5.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton6
            // 
            this.daUiButton6.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton6.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton6.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton6.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton6.FillColor = System.Drawing.Color.Silver;
            this.daUiButton6.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton6.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton6.Location = new System.Drawing.Point(517, 266);
            this.daUiButton6.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton6.Name = "daUiButton6";
            this.daUiButton6.PLC_Enable = true;
            this.daUiButton6.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton6.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton6.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton6.pLCBitselectRealize.BitPattern = false;
            this.daUiButton6.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton6.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton6.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton6.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton6.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton6.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton6.pLCBitselectRealize.OutReverse = false;
            this.daUiButton6.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton6.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton6.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton6.pLCBitselectRealize.ReadWriteAddress = "9021.5";
            this.daUiButton6.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton6.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton6.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton6.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton6.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton6.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton6.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton6.pLCBitselectRealize.Speech = false;
            this.daUiButton6.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton6.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton6.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton6.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton6.pLCBitselectRealize.TextContent_0 = "工作复位";
            this.daUiButton6.pLCBitselectRealize.TextContent_1 = "工作复位中";
            this.daUiButton6.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton6.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton6.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton6.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton6.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton6.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton6.pLCBitselectRealize.TextState = 0;
            this.daUiButton6.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton6.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton6.pLCBitselectRealize.WriteAddress = "8300.0";
            this.daUiButton6.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton6.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton6.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton6.Size = new System.Drawing.Size(105, 47);
            this.daUiButton6.TabIndex = 69;
            this.daUiButton6.Text = "工作复位";
            this.daUiButton6.Textalign_0 = "MiddleCenter";
            this.daUiButton6.Textalign_1 = "MiddleCenter";
            this.daUiButton6.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton6.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton6.TextContent_0 = "工作复位";
            this.daUiButton6.TextContent_1 = "工作复位中";
            this.daUiButton6.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton6.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton7
            // 
            this.daUiButton7.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton7.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton7.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton7.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton7.FillColor = System.Drawing.Color.Silver;
            this.daUiButton7.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton7.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton7.Location = new System.Drawing.Point(651, 266);
            this.daUiButton7.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton7.Name = "daUiButton7";
            this.daUiButton7.PLC_Enable = true;
            this.daUiButton7.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton7.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton7.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton7.pLCBitselectRealize.BitPattern = false;
            this.daUiButton7.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton7.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton7.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton7.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton7.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton7.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton7.pLCBitselectRealize.OutReverse = false;
            this.daUiButton7.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton7.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton7.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton7.pLCBitselectRealize.ReadWriteAddress = "9021.7";
            this.daUiButton7.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton7.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton7.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton7.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton7.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton7.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton7.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton7.pLCBitselectRealize.Speech = false;
            this.daUiButton7.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton7.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton7.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton7.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton7.pLCBitselectRealize.TextContent_0 = "原点回归";
            this.daUiButton7.pLCBitselectRealize.TextContent_1 = "原点回归完成";
            this.daUiButton7.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton7.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton7.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton7.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton7.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton7.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton7.pLCBitselectRealize.TextState = 0;
            this.daUiButton7.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton7.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton7.pLCBitselectRealize.WriteAddress = "9021.6";
            this.daUiButton7.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton7.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton7.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton7.Size = new System.Drawing.Size(105, 47);
            this.daUiButton7.TabIndex = 70;
            this.daUiButton7.Text = "原点回归";
            this.daUiButton7.Textalign_0 = "MiddleCenter";
            this.daUiButton7.Textalign_1 = "MiddleCenter";
            this.daUiButton7.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton7.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton7.TextContent_0 = "原点回归";
            this.daUiButton7.TextContent_1 = "原点回归完成";
            this.daUiButton7.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton7.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // ZWJ手动界面
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(897, 679);
            this.Name = "ZWJ手动界面";
            this.Text = "ZWJ手动界面";
            this.uiPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private 基础控件.DAUiButton daUiButton6;
        private 基础控件.DAUiButton daUiButton7;
        private 基础控件.DAUiButton daUiButton4;
        private 基础控件.DAUiButton daUiButton5;
        private 基础控件.DAUiButton daUiButton18;
        private 基础控件.DAUiButton daUiButton19;
        private 基础控件.DAUiButton daUiButton20;
        private 基础控件.DAUiButton daUiButton21;
        private 基础控件.DAUiButton daUiButton22;
        private 基础控件.DAUiButton daUiButton23;
        private 基础控件.DAUiButton daUiButton2;
        private 基础控件.DAUiButton daUiButton3;
        private 基础控件.DAUiButton daUiButton31;
        private 基础控件.DAUiButton daUiButton1;
    }
}