
namespace PLC通讯基础控件项目.模板与控制界面.三区手动界面
{
    partial class PY05手动界面
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.daUiButton16 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton14 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton25 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton27 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton28 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton29 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton4 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton19 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton31 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton1 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton2 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton3 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.uiPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // uiPanel1
            // 
            this.uiPanel1.Controls.Add(this.daUiButton2);
            this.uiPanel1.Controls.Add(this.daUiButton3);
            this.uiPanel1.Controls.Add(this.daUiButton16);
            this.uiPanel1.Controls.Add(this.daUiButton25);
            this.uiPanel1.Controls.Add(this.daUiButton27);
            this.uiPanel1.Controls.Add(this.daUiButton28);
            this.uiPanel1.Controls.Add(this.daUiButton29);
            this.uiPanel1.Controls.Add(this.daUiButton31);
            this.uiPanel1.Controls.Add(this.daUiButton1);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton1, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton31, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction2, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton29, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton28, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction1, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton27, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction3, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton25, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction4, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction5, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton16, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton3, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton2, 0);
            // 
            // daUiButton16
            // 
            this.daUiButton16.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton16.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton16.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton16.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton16.FillColor = System.Drawing.Color.Silver;
            this.daUiButton16.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton16.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton16.Location = new System.Drawing.Point(537, 256);
            this.daUiButton16.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton16.Name = "daUiButton16";
            this.daUiButton16.PLC_Enable = true;
            this.daUiButton16.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton16.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton16.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton16.pLCBitselectRealize.BitPattern = false;
            this.daUiButton16.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton16.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton16.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton16.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton16.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton16.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton16.pLCBitselectRealize.OutReverse = false;
            this.daUiButton16.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton16.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton16.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton16.pLCBitselectRealize.ReadWriteAddress = "8608.5";
            this.daUiButton16.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton16.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton16.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton16.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton16.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton16.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton16.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton16.pLCBitselectRealize.Speech = false;
            this.daUiButton16.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton16.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton16.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton16.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton16.pLCBitselectRealize.TextContent_0 = "  移栽\n到取料位";
            this.daUiButton16.pLCBitselectRealize.TextContent_1 = "  移栽\n到取料位";
            this.daUiButton16.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton16.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton16.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton16.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton16.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton16.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton16.pLCBitselectRealize.TextState = 0;
            this.daUiButton16.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton16.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton16.pLCBitselectRealize.WriteAddress = "9020.6";
            this.daUiButton16.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton16.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton16.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton16.Size = new System.Drawing.Size(105, 47);
            this.daUiButton16.TabIndex = 185;
            this.daUiButton16.Text = "  移栽\n到取料位";
            this.daUiButton16.Textalign_0 = "MiddleCenter";
            this.daUiButton16.Textalign_1 = "MiddleCenter";
            this.daUiButton16.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton16.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton16.TextContent_0 = "  移栽\n到取料位";
            this.daUiButton16.TextContent_1 = "  移栽\n到取料位";
            this.daUiButton16.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton16.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton14
            // 
            this.daUiButton14.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton14.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton14.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton14.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton14.FillColor = System.Drawing.Color.Silver;
            this.daUiButton14.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton14.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton14.Location = new System.Drawing.Point(737, 498);
            this.daUiButton14.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton14.Name = "daUiButton14";
            this.daUiButton14.PLC_Enable = true;
            this.daUiButton14.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton14.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton14.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton14.pLCBitselectRealize.BitPattern = false;
            this.daUiButton14.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton14.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton14.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton14.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton14.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton14.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton14.pLCBitselectRealize.OutReverse = false;
            this.daUiButton14.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton14.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton14.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton14.pLCBitselectRealize.ReadWriteAddress = "3.5";
            this.daUiButton14.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton14.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton14.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton14.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton14.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton14.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton14.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton14.pLCBitselectRealize.Speech = false;
            this.daUiButton14.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton14.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton14.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton14.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton14.pLCBitselectRealize.TextContent_0 = "启动";
            this.daUiButton14.pLCBitselectRealize.TextContent_1 = "启动";
            this.daUiButton14.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton14.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton14.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton14.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton14.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton14.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton14.pLCBitselectRealize.TextState = 0;
            this.daUiButton14.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton14.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton14.pLCBitselectRealize.WriteAddress = "8483.3";
            this.daUiButton14.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton14.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton14.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton14.Size = new System.Drawing.Size(105, 47);
            this.daUiButton14.TabIndex = 184;
            this.daUiButton14.Text = "启动";
            this.daUiButton14.Textalign_0 = "MiddleCenter";
            this.daUiButton14.Textalign_1 = "MiddleCenter";
            this.daUiButton14.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton14.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton14.TextContent_0 = "启动";
            this.daUiButton14.TextContent_1 = "启动";
            this.daUiButton14.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton14.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton25
            // 
            this.daUiButton25.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton25.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton25.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(19)))), ((int)(((byte)(59)))));
            this.daUiButton25.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton25.FillColor = System.Drawing.Color.Silver;
            this.daUiButton25.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton25.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton25.Location = new System.Drawing.Point(671, 161);
            this.daUiButton25.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton25.Name = "daUiButton25";
            this.daUiButton25.PLC_Enable = true;
            this.daUiButton25.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton25.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton25.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(19)))), ((int)(((byte)(59)))));
            this.daUiButton25.pLCBitselectRealize.BitPattern = false;
            this.daUiButton25.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton25.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton25.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton25.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton25.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton25.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton25.pLCBitselectRealize.OutReverse = false;
            this.daUiButton25.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton25.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton25.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton25.pLCBitselectRealize.ReadWriteAddress = "5710.2";
            this.daUiButton25.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton25.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton25.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton25.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton25.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton25.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton25.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton25.pLCBitselectRealize.Speech = false;
            this.daUiButton25.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton25.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton25.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton25.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton25.pLCBitselectRealize.TextContent_0 = "故障复位";
            this.daUiButton25.pLCBitselectRealize.TextContent_1 = "故障中";
            this.daUiButton25.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton25.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton25.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton25.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton25.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton25.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton25.pLCBitselectRealize.TextState = 0;
            this.daUiButton25.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton25.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton25.pLCBitselectRealize.WriteAddress = "8601.7";
            this.daUiButton25.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton25.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton25.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton25.Size = new System.Drawing.Size(105, 47);
            this.daUiButton25.TabIndex = 183;
            this.daUiButton25.Text = "故障复位";
            this.daUiButton25.Textalign_0 = "MiddleCenter";
            this.daUiButton25.Textalign_1 = "MiddleCenter";
            this.daUiButton25.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton25.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton25.TextContent_0 = "故障复位";
            this.daUiButton25.TextContent_1 = "故障中";
            this.daUiButton25.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton25.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton27
            // 
            this.daUiButton27.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton27.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton27.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton27.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton27.FillColor = System.Drawing.Color.Silver;
            this.daUiButton27.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton27.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton27.Location = new System.Drawing.Point(537, 161);
            this.daUiButton27.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton27.Name = "daUiButton27";
            this.daUiButton27.PLC_Enable = true;
            this.daUiButton27.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton27.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton27.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton27.pLCBitselectRealize.BitPattern = false;
            this.daUiButton27.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton27.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton27.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton27.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton27.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton27.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton27.pLCBitselectRealize.OutReverse = false;
            this.daUiButton27.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.selector_witch;
            this.daUiButton27.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton27.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton27.pLCBitselectRealize.ReadWriteAddress = "8601.6";
            this.daUiButton27.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton27.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton27.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton27.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton27.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton27.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton27.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton27.pLCBitselectRealize.Speech = false;
            this.daUiButton27.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton27.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton27.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton27.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton27.pLCBitselectRealize.TextContent_0 = " 伺服\n使能关";
            this.daUiButton27.pLCBitselectRealize.TextContent_1 = "  伺服\n使能关中";
            this.daUiButton27.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton27.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton27.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton27.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton27.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton27.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton27.pLCBitselectRealize.TextState = 0;
            this.daUiButton27.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton27.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton27.pLCBitselectRealize.WriteAddress = "9020.6";
            this.daUiButton27.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton27.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton27.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton27.Size = new System.Drawing.Size(105, 47);
            this.daUiButton27.TabIndex = 182;
            this.daUiButton27.Text = " 伺服\n使能关";
            this.daUiButton27.Textalign_0 = "MiddleCenter";
            this.daUiButton27.Textalign_1 = "MiddleCenter";
            this.daUiButton27.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton27.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton27.TextContent_0 = " 伺服\n使能关";
            this.daUiButton27.TextContent_1 = "  伺服\n使能关中";
            this.daUiButton27.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton27.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton28
            // 
            this.daUiButton28.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton28.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton28.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton28.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton28.FillColor = System.Drawing.Color.Silver;
            this.daUiButton28.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton28.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton28.Location = new System.Drawing.Point(537, 65);
            this.daUiButton28.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton28.Name = "daUiButton28";
            this.daUiButton28.PLC_Enable = true;
            this.daUiButton28.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton28.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton28.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton28.pLCBitselectRealize.BitPattern = false;
            this.daUiButton28.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton28.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton28.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton28.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton28.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton28.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton28.pLCBitselectRealize.OutReverse = false;
            this.daUiButton28.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton28.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton28.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton28.pLCBitselectRealize.ReadWriteAddress = "8602.5";
            this.daUiButton28.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton28.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton28.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton28.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton28.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton28.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton28.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton28.pLCBitselectRealize.Speech = false;
            this.daUiButton28.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton28.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton28.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton28.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton28.pLCBitselectRealize.TextContent_0 = "移栽移动\n到焊机位";
            this.daUiButton28.pLCBitselectRealize.TextContent_1 = "移栽移动\n到焊机位";
            this.daUiButton28.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton28.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton28.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton28.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton28.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton28.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton28.pLCBitselectRealize.TextState = 0;
            this.daUiButton28.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton28.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton28.pLCBitselectRealize.WriteAddress = "9020.4";
            this.daUiButton28.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton28.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton28.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton28.Size = new System.Drawing.Size(105, 47);
            this.daUiButton28.TabIndex = 180;
            this.daUiButton28.Text = "移栽移动\n到焊机位";
            this.daUiButton28.Textalign_0 = "MiddleCenter";
            this.daUiButton28.Textalign_1 = "MiddleCenter";
            this.daUiButton28.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton28.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton28.TextContent_0 = "移栽移动\n到焊机位";
            this.daUiButton28.TextContent_1 = "移栽移动\n到焊机位";
            this.daUiButton28.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton28.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton29
            // 
            this.daUiButton29.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton29.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton29.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton29.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton29.FillColor = System.Drawing.Color.Silver;
            this.daUiButton29.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton29.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton29.Location = new System.Drawing.Point(671, 65);
            this.daUiButton29.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton29.Name = "daUiButton29";
            this.daUiButton29.PLC_Enable = true;
            this.daUiButton29.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton29.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton29.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton29.pLCBitselectRealize.BitPattern = false;
            this.daUiButton29.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton29.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton29.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton29.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton29.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton29.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton29.pLCBitselectRealize.OutReverse = false;
            this.daUiButton29.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton29.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton29.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton29.pLCBitselectRealize.ReadWriteAddress = "8602.6";
            this.daUiButton29.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton29.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton29.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton29.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton29.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton29.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton29.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton29.pLCBitselectRealize.Speech = false;
            this.daUiButton29.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton29.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton29.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton29.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton29.pLCBitselectRealize.TextContent_0 = "   移栽\n至原位位";
            this.daUiButton29.pLCBitselectRealize.TextContent_1 = "   移栽\n至原位中";
            this.daUiButton29.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton29.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton29.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton29.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton29.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton29.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton29.pLCBitselectRealize.TextState = 0;
            this.daUiButton29.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton29.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton29.pLCBitselectRealize.WriteAddress = "9020.5";
            this.daUiButton29.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton29.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton29.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton29.Size = new System.Drawing.Size(105, 47);
            this.daUiButton29.TabIndex = 181;
            this.daUiButton29.Text = "   移栽\n至原位位";
            this.daUiButton29.Textalign_0 = "MiddleCenter";
            this.daUiButton29.Textalign_1 = "MiddleCenter";
            this.daUiButton29.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton29.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton29.TextContent_0 = "   移栽\n至原位位";
            this.daUiButton29.TextContent_1 = "   移栽\n至原位中";
            this.daUiButton29.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton29.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton4
            // 
            this.daUiButton4.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton4.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton4.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton4.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton4.FillColor = System.Drawing.Color.Silver;
            this.daUiButton4.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton4.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.Location = new System.Drawing.Point(577, 498);
            this.daUiButton4.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton4.Name = "daUiButton4";
            this.daUiButton4.PLC_Enable = true;
            this.daUiButton4.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton4.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton4.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton4.pLCBitselectRealize.BitPattern = false;
            this.daUiButton4.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton4.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton4.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton4.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton4.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton4.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton4.pLCBitselectRealize.OutReverse = false;
            this.daUiButton4.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton4.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton4.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton4.pLCBitselectRealize.ReadWriteAddress = "5702.2";
            this.daUiButton4.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton4.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton4.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton4.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton4.pLCBitselectRealize.Speech = false;
            this.daUiButton4.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton4.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton4.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton4.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton4.pLCBitselectRealize.TextContent_0 = "回原位";
            this.daUiButton4.pLCBitselectRealize.TextContent_1 = "  原点\n回归完成";
            this.daUiButton4.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton4.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton4.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton4.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton4.pLCBitselectRealize.TextState = 0;
            this.daUiButton4.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton4.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton4.pLCBitselectRealize.WriteAddress = "8602.1";
            this.daUiButton4.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton4.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton4.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton4.Size = new System.Drawing.Size(105, 47);
            this.daUiButton4.TabIndex = 179;
            this.daUiButton4.Text = "回原位";
            this.daUiButton4.Textalign_0 = "MiddleCenter";
            this.daUiButton4.Textalign_1 = "MiddleCenter";
            this.daUiButton4.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton4.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton4.TextContent_0 = "回原位";
            this.daUiButton4.TextContent_1 = "  原点\n回归完成";
            this.daUiButton4.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton19
            // 
            this.daUiButton19.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton19.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton19.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.daUiButton19.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton19.FillColor = System.Drawing.Color.Silver;
            this.daUiButton19.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton19.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.Location = new System.Drawing.Point(420, 498);
            this.daUiButton19.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton19.Name = "daUiButton19";
            this.daUiButton19.PLC_Enable = true;
            this.daUiButton19.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton19.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton19.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.daUiButton19.pLCBitselectRealize.BitPattern = false;
            this.daUiButton19.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton19.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton19.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton19.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton19.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton19.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton19.pLCBitselectRealize.OutReverse = false;
            this.daUiButton19.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton19.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton19.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton19.pLCBitselectRealize.ReadWriteAddress = "8602.0";
            this.daUiButton19.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton19.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton19.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton19.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton19.pLCBitselectRealize.Speech = false;
            this.daUiButton19.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton19.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton19.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton19.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton19.pLCBitselectRealize.TextContent_0 = "复位";
            this.daUiButton19.pLCBitselectRealize.TextContent_1 = "复位";
            this.daUiButton19.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton19.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton19.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton19.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton19.pLCBitselectRealize.TextState = 0;
            this.daUiButton19.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton19.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton19.pLCBitselectRealize.WriteAddress = "8131.0";
            this.daUiButton19.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton19.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton19.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton19.Size = new System.Drawing.Size(105, 47);
            this.daUiButton19.TabIndex = 178;
            this.daUiButton19.Text = "复位";
            this.daUiButton19.Textalign_0 = "MiddleCenter";
            this.daUiButton19.Textalign_1 = "MiddleCenter";
            this.daUiButton19.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton19.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton19.TextContent_0 = "复位";
            this.daUiButton19.TextContent_1 = "复位";
            this.daUiButton19.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton31
            // 
            this.daUiButton31.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton31.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton31.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton31.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton31.FillColor = System.Drawing.Color.Silver;
            this.daUiButton31.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton31.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.Location = new System.Drawing.Point(89, 65);
            this.daUiButton31.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton31.Name = "daUiButton31";
            this.daUiButton31.PLC_Enable = true;
            this.daUiButton31.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton31.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton31.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton31.pLCBitselectRealize.BitPattern = false;
            this.daUiButton31.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton31.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton31.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton31.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton31.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton31.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton31.pLCBitselectRealize.OutReverse = false;
            this.daUiButton31.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton31.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton31.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton31.pLCBitselectRealize.ReadWriteAddress = "508.1";
            this.daUiButton31.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton31.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton31.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton31.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton31.pLCBitselectRealize.Speech = false;
            this.daUiButton31.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton31.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton31.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton31.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton31.pLCBitselectRealize.TextContent_0 = "升降\n下降";
            this.daUiButton31.pLCBitselectRealize.TextContent_1 = " 升降\n下降中";
            this.daUiButton31.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton31.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton31.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton31.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton31.pLCBitselectRealize.TextState = 0;
            this.daUiButton31.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton31.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton31.pLCBitselectRealize.WriteAddress = "8601.2";
            this.daUiButton31.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton31.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton31.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton31.Size = new System.Drawing.Size(105, 47);
            this.daUiButton31.TabIndex = 172;
            this.daUiButton31.Text = "升降\n下降";
            this.daUiButton31.Textalign_0 = "MiddleCenter";
            this.daUiButton31.Textalign_1 = "MiddleCenter";
            this.daUiButton31.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton31.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton31.TextContent_0 = "升降\n下降";
            this.daUiButton31.TextContent_1 = " 升降\n下降中";
            this.daUiButton31.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton1
            // 
            this.daUiButton1.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton1.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton1.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton1.FillColor = System.Drawing.Color.Silver;
            this.daUiButton1.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton1.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.Location = new System.Drawing.Point(223, 65);
            this.daUiButton1.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton1.Name = "daUiButton1";
            this.daUiButton1.PLC_Enable = true;
            this.daUiButton1.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton1.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton1.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton1.pLCBitselectRealize.BitPattern = false;
            this.daUiButton1.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton1.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton1.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton1.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton1.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton1.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton1.pLCBitselectRealize.OutReverse = false;
            this.daUiButton1.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton1.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton1.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton1.pLCBitselectRealize.ReadWriteAddress = "508.0";
            this.daUiButton1.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton1.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton1.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton1.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton1.pLCBitselectRealize.Speech = false;
            this.daUiButton1.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton1.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton1.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton1.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton1.pLCBitselectRealize.TextContent_0 = "升降\n上升";
            this.daUiButton1.pLCBitselectRealize.TextContent_1 = " 升降\n上升中";
            this.daUiButton1.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton1.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton1.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton1.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton1.pLCBitselectRealize.TextState = 0;
            this.daUiButton1.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton1.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton1.pLCBitselectRealize.WriteAddress = "8601.3";
            this.daUiButton1.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton1.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton1.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton1.Size = new System.Drawing.Size(105, 47);
            this.daUiButton1.TabIndex = 173;
            this.daUiButton1.Text = "升降\n上升";
            this.daUiButton1.Textalign_0 = "MiddleCenter";
            this.daUiButton1.Textalign_1 = "MiddleCenter";
            this.daUiButton1.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton1.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton1.TextContent_0 = "升降\n上升";
            this.daUiButton1.TextContent_1 = " 升降\n上升中";
            this.daUiButton1.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton2
            // 
            this.daUiButton2.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton2.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton2.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(19)))), ((int)(((byte)(59)))));
            this.daUiButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton2.FillColor = System.Drawing.Color.Silver;
            this.daUiButton2.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton2.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.Location = new System.Drawing.Point(223, 256);
            this.daUiButton2.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton2.Name = "daUiButton2";
            this.daUiButton2.PLC_Enable = true;
            this.daUiButton2.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton2.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton2.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(19)))), ((int)(((byte)(59)))));
            this.daUiButton2.pLCBitselectRealize.BitPattern = false;
            this.daUiButton2.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton2.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton2.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton2.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton2.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton2.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton2.pLCBitselectRealize.OutReverse = false;
            this.daUiButton2.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton2.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton2.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton2.pLCBitselectRealize.ReadWriteAddress = "8603.0";
            this.daUiButton2.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton2.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton2.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton2.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton2.pLCBitselectRealize.Speech = false;
            this.daUiButton2.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton2.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton2.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton2.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton2.pLCBitselectRealize.TextContent_0 = "移栽点动-";
            this.daUiButton2.pLCBitselectRealize.TextContent_1 = "移栽点动-";
            this.daUiButton2.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton2.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton2.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton2.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton2.pLCBitselectRealize.TextState = 0;
            this.daUiButton2.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton2.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton2.pLCBitselectRealize.WriteAddress = "8476.2";
            this.daUiButton2.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton2.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton2.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton2.Size = new System.Drawing.Size(105, 47);
            this.daUiButton2.TabIndex = 188;
            this.daUiButton2.Text = "移栽点动-";
            this.daUiButton2.Textalign_0 = "MiddleCenter";
            this.daUiButton2.Textalign_1 = "MiddleCenter";
            this.daUiButton2.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton2.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton2.TextContent_0 = "移栽点动-";
            this.daUiButton2.TextContent_1 = "移栽点动-";
            this.daUiButton2.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton3
            // 
            this.daUiButton3.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton3.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton3.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton3.FillColor = System.Drawing.Color.Silver;
            this.daUiButton3.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton3.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.Location = new System.Drawing.Point(89, 256);
            this.daUiButton3.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton3.Name = "daUiButton3";
            this.daUiButton3.PLC_Enable = true;
            this.daUiButton3.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton3.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton3.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton3.pLCBitselectRealize.BitPattern = false;
            this.daUiButton3.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton3.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton3.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton3.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton3.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton3.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton3.pLCBitselectRealize.OutReverse = false;
            this.daUiButton3.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton3.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton3.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton3.pLCBitselectRealize.ReadWriteAddress = "8602.7";
            this.daUiButton3.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton3.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton3.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton3.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton3.pLCBitselectRealize.Speech = false;
            this.daUiButton3.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton3.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton3.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton3.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton3.pLCBitselectRealize.TextContent_0 = "移栽点动+";
            this.daUiButton3.pLCBitselectRealize.TextContent_1 = "移栽点动+";
            this.daUiButton3.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton3.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton3.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton3.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton3.pLCBitselectRealize.TextState = 0;
            this.daUiButton3.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton3.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton3.pLCBitselectRealize.WriteAddress = "9020.6";
            this.daUiButton3.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton3.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton3.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton3.Size = new System.Drawing.Size(105, 47);
            this.daUiButton3.TabIndex = 187;
            this.daUiButton3.Text = "移栽点动+";
            this.daUiButton3.Textalign_0 = "MiddleCenter";
            this.daUiButton3.Textalign_1 = "MiddleCenter";
            this.daUiButton3.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton3.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton3.TextContent_0 = "移栽点动+";
            this.daUiButton3.TextContent_1 = "移栽点动+";
            this.daUiButton3.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // PY05手动界面
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(897, 679);
            this.Controls.Add(this.daUiButton14);
            this.Controls.Add(this.daUiButton4);
            this.Controls.Add(this.daUiButton19);
            this.Name = "PY05手动界面";
            this.Text = "PY05手动界面";
            this.Controls.SetChildIndex(this.uiPanel1, 0);
            this.Controls.SetChildIndex(this.daUiButton19, 0);
            this.Controls.SetChildIndex(this.daUiButton4, 0);
            this.Controls.SetChildIndex(this.daUiButton14, 0);
            this.uiPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private 基础控件.DAUiButton daUiButton16;
        private 基础控件.DAUiButton daUiButton14;
        private 基础控件.DAUiButton daUiButton25;
        private 基础控件.DAUiButton daUiButton27;
        private 基础控件.DAUiButton daUiButton28;
        private 基础控件.DAUiButton daUiButton29;
        private 基础控件.DAUiButton daUiButton4;
        private 基础控件.DAUiButton daUiButton19;
        private 基础控件.DAUiButton daUiButton31;
        private 基础控件.DAUiButton daUiButton1;
        private 基础控件.DAUiButton daUiButton2;
        private 基础控件.DAUiButton daUiButton3;
    }
}