
namespace PLC通讯基础控件项目.模板与控制界面.三区手动界面
{
    partial class 新ZDP手动界面
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.daUiButton7 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton8 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton5 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton6 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton2 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton3 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton31 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton1 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton4 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.daUiButton19 = new PLC通讯基础控件项目.基础控件.DAUiButton();
            this.uiPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // uiPanel1
            // 
            this.uiPanel1.Controls.Add(this.daUiButton7);
            this.uiPanel1.Controls.Add(this.daUiButton8);
            this.uiPanel1.Controls.Add(this.daUiButton5);
            this.uiPanel1.Controls.Add(this.daUiButton6);
            this.uiPanel1.Controls.Add(this.daUiButton2);
            this.uiPanel1.Controls.Add(this.daUiButton3);
            this.uiPanel1.Controls.Add(this.daUiButton31);
            this.uiPanel1.Controls.Add(this.daUiButton19);
            this.uiPanel1.Controls.Add(this.daUiButton4);
            this.uiPanel1.Controls.Add(this.daUiButton1);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton1, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton4, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton19, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton31, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction2, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton3, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction1, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton2, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction3, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton6, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction4, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton5, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daPlcFunction5, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton8, 0);
            this.uiPanel1.Controls.SetChildIndex(this.daUiButton7, 0);
            // 
            // daUiButton7
            // 
            this.daUiButton7.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton7.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton7.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(19)))), ((int)(((byte)(59)))));
            this.daUiButton7.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton7.FillColor = System.Drawing.Color.Silver;
            this.daUiButton7.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton7.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton7.Location = new System.Drawing.Point(240, 335);
            this.daUiButton7.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton7.Name = "daUiButton7";
            this.daUiButton7.PLC_Enable = true;
            this.daUiButton7.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton7.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton7.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(19)))), ((int)(((byte)(59)))));
            this.daUiButton7.pLCBitselectRealize.BitPattern = false;
            this.daUiButton7.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton7.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton7.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton7.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton7.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton7.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton7.pLCBitselectRealize.OutReverse = false;
            this.daUiButton7.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton7.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton7.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton7.pLCBitselectRealize.ReadWriteAddress = "507.7";
            this.daUiButton7.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton7.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton7.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton7.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton7.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton7.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton7.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton7.pLCBitselectRealize.Speech = false;
            this.daUiButton7.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton7.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton7.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton7.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton7.pLCBitselectRealize.TextContent_0 = "定位销关";
            this.daUiButton7.pLCBitselectRealize.TextContent_1 = "  定位\n销关中";
            this.daUiButton7.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton7.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton7.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton7.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton7.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton7.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton7.pLCBitselectRealize.TextState = 0;
            this.daUiButton7.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton7.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton7.pLCBitselectRealize.WriteAddress = "11.2";
            this.daUiButton7.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton7.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton7.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton7.Size = new System.Drawing.Size(105, 47);
            this.daUiButton7.TabIndex = 218;
            this.daUiButton7.Text = "定位销关";
            this.daUiButton7.Textalign_0 = "MiddleCenter";
            this.daUiButton7.Textalign_1 = "MiddleCenter";
            this.daUiButton7.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton7.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton7.TextContent_0 = "定位销关";
            this.daUiButton7.TextContent_1 = "  定位\n销关中";
            this.daUiButton7.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton7.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton8
            // 
            this.daUiButton8.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton8.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton8.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton8.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton8.FillColor = System.Drawing.Color.Silver;
            this.daUiButton8.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton8.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton8.Location = new System.Drawing.Point(106, 335);
            this.daUiButton8.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton8.Name = "daUiButton8";
            this.daUiButton8.PLC_Enable = true;
            this.daUiButton8.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton8.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton8.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton8.pLCBitselectRealize.BitPattern = false;
            this.daUiButton8.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton8.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton8.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton8.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton8.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton8.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton8.pLCBitselectRealize.OutReverse = false;
            this.daUiButton8.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton8.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton8.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton8.pLCBitselectRealize.ReadWriteAddress = "507.6";
            this.daUiButton8.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton8.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton8.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton8.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton8.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton8.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton8.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton8.pLCBitselectRealize.Speech = false;
            this.daUiButton8.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton8.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton8.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton8.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton8.pLCBitselectRealize.TextContent_0 = "定位销开";
            this.daUiButton8.pLCBitselectRealize.TextContent_1 = " 定位\n销开中";
            this.daUiButton8.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton8.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton8.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton8.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton8.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton8.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton8.pLCBitselectRealize.TextState = 0;
            this.daUiButton8.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton8.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton8.pLCBitselectRealize.WriteAddress = "11.1";
            this.daUiButton8.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton8.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton8.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton8.Size = new System.Drawing.Size(105, 47);
            this.daUiButton8.TabIndex = 217;
            this.daUiButton8.Text = "定位销开";
            this.daUiButton8.Textalign_0 = "MiddleCenter";
            this.daUiButton8.Textalign_1 = "MiddleCenter";
            this.daUiButton8.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton8.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton8.TextContent_0 = "定位销开";
            this.daUiButton8.TextContent_1 = " 定位\n销开中";
            this.daUiButton8.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton8.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton5
            // 
            this.daUiButton5.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton5.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton5.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton5.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton5.FillColor = System.Drawing.Color.Silver;
            this.daUiButton5.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton5.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.Location = new System.Drawing.Point(106, 150);
            this.daUiButton5.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton5.Name = "daUiButton5";
            this.daUiButton5.PLC_Enable = true;
            this.daUiButton5.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton5.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton5.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton5.pLCBitselectRealize.BitPattern = false;
            this.daUiButton5.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton5.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton5.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton5.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton5.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton5.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton5.pLCBitselectRealize.OutReverse = false;
            this.daUiButton5.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton5.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton5.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton5.pLCBitselectRealize.ReadWriteAddress = "511.2";
            this.daUiButton5.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton5.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton5.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton5.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton5.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton5.pLCBitselectRealize.Speech = false;
            this.daUiButton5.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton5.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton5.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton5.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton5.pLCBitselectRealize.TextContent_0 = " 斜向\n定位开";
            this.daUiButton5.pLCBitselectRealize.TextContent_1 = "  斜向\n定位开中";
            this.daUiButton5.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton5.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton5.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton5.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton5.pLCBitselectRealize.TextState = 0;
            this.daUiButton5.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton5.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton5.pLCBitselectRealize.WriteAddress = "2.5";
            this.daUiButton5.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton5.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton5.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton5.Size = new System.Drawing.Size(105, 47);
            this.daUiButton5.TabIndex = 215;
            this.daUiButton5.Text = " 斜向\n定位开";
            this.daUiButton5.Textalign_0 = "MiddleCenter";
            this.daUiButton5.Textalign_1 = "MiddleCenter";
            this.daUiButton5.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton5.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton5.TextContent_0 = " 斜向\n定位开";
            this.daUiButton5.TextContent_1 = "  斜向\n定位开中";
            this.daUiButton5.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton5.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton6
            // 
            this.daUiButton6.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton6.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton6.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton6.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton6.FillColor = System.Drawing.Color.Silver;
            this.daUiButton6.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton6.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton6.Location = new System.Drawing.Point(240, 150);
            this.daUiButton6.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton6.Name = "daUiButton6";
            this.daUiButton6.PLC_Enable = true;
            this.daUiButton6.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton6.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton6.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton6.pLCBitselectRealize.BitPattern = false;
            this.daUiButton6.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton6.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton6.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton6.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton6.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton6.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton6.pLCBitselectRealize.OutReverse = false;
            this.daUiButton6.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton6.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton6.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton6.pLCBitselectRealize.ReadWriteAddress = "511.3";
            this.daUiButton6.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton6.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton6.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton6.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton6.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton6.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton6.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton6.pLCBitselectRealize.Speech = false;
            this.daUiButton6.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton6.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton6.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton6.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton6.pLCBitselectRealize.TextContent_0 = " 斜向\n定位关";
            this.daUiButton6.pLCBitselectRealize.TextContent_1 = "  斜向\n定位关中";
            this.daUiButton6.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton6.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton6.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton6.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton6.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton6.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton6.pLCBitselectRealize.TextState = 0;
            this.daUiButton6.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton6.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton6.pLCBitselectRealize.WriteAddress = "2.6";
            this.daUiButton6.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton6.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton6.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton6.Size = new System.Drawing.Size(105, 47);
            this.daUiButton6.TabIndex = 216;
            this.daUiButton6.Text = " 斜向\n定位关";
            this.daUiButton6.Textalign_0 = "MiddleCenter";
            this.daUiButton6.Textalign_1 = "MiddleCenter";
            this.daUiButton6.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton6.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton6.TextContent_0 = " 斜向\n定位关";
            this.daUiButton6.TextContent_1 = "  斜向\n定位关中";
            this.daUiButton6.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton6.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton2
            // 
            this.daUiButton2.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton2.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton2.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(19)))), ((int)(((byte)(59)))));
            this.daUiButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton2.FillColor = System.Drawing.Color.Silver;
            this.daUiButton2.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton2.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.Location = new System.Drawing.Point(240, 245);
            this.daUiButton2.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton2.Name = "daUiButton2";
            this.daUiButton2.PLC_Enable = true;
            this.daUiButton2.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton2.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton2.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(19)))), ((int)(((byte)(59)))));
            this.daUiButton2.pLCBitselectRealize.BitPattern = false;
            this.daUiButton2.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton2.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton2.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton2.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton2.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton2.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton2.pLCBitselectRealize.OutReverse = false;
            this.daUiButton2.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton2.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton2.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton2.pLCBitselectRealize.ReadWriteAddress = "504.3";
            this.daUiButton2.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton2.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton2.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton2.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton2.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton2.pLCBitselectRealize.Speech = false;
            this.daUiButton2.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton2.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton2.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton2.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton2.pLCBitselectRealize.TextContent_0 = " 物料\n定位关";
            this.daUiButton2.pLCBitselectRealize.TextContent_1 = "  物料\n定位关中";
            this.daUiButton2.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton2.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton2.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton2.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton2.pLCBitselectRealize.TextState = 0;
            this.daUiButton2.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton2.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton2.pLCBitselectRealize.WriteAddress = "8.3";
            this.daUiButton2.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton2.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton2.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton2.Size = new System.Drawing.Size(105, 47);
            this.daUiButton2.TabIndex = 214;
            this.daUiButton2.Text = " 物料\n定位关";
            this.daUiButton2.Textalign_0 = "MiddleCenter";
            this.daUiButton2.Textalign_1 = "MiddleCenter";
            this.daUiButton2.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton2.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton2.TextContent_0 = " 物料\n定位关";
            this.daUiButton2.TextContent_1 = "  物料\n定位关中";
            this.daUiButton2.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton2.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton3
            // 
            this.daUiButton3.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton3.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton3.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton3.FillColor = System.Drawing.Color.Silver;
            this.daUiButton3.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton3.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.Location = new System.Drawing.Point(106, 245);
            this.daUiButton3.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton3.Name = "daUiButton3";
            this.daUiButton3.PLC_Enable = true;
            this.daUiButton3.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton3.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton3.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton3.pLCBitselectRealize.BitPattern = false;
            this.daUiButton3.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton3.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton3.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton3.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton3.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton3.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton3.pLCBitselectRealize.OutReverse = false;
            this.daUiButton3.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton3.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton3.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton3.pLCBitselectRealize.ReadWriteAddress = "504.7";
            this.daUiButton3.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton3.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton3.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton3.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton3.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton3.pLCBitselectRealize.Speech = false;
            this.daUiButton3.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton3.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton3.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton3.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton3.pLCBitselectRealize.TextContent_0 = " 物料\n定位开";
            this.daUiButton3.pLCBitselectRealize.TextContent_1 = "  物料\n定位开中";
            this.daUiButton3.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton3.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton3.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton3.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton3.pLCBitselectRealize.TextState = 0;
            this.daUiButton3.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton3.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton3.pLCBitselectRealize.WriteAddress = "8.2";
            this.daUiButton3.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton3.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton3.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton3.Size = new System.Drawing.Size(105, 47);
            this.daUiButton3.TabIndex = 213;
            this.daUiButton3.Text = " 物料\n定位开";
            this.daUiButton3.Textalign_0 = "MiddleCenter";
            this.daUiButton3.Textalign_1 = "MiddleCenter";
            this.daUiButton3.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton3.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton3.TextContent_0 = " 物料\n定位开";
            this.daUiButton3.TextContent_1 = "  物料\n定位开中";
            this.daUiButton3.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton3.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton31
            // 
            this.daUiButton31.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton31.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton31.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton31.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton31.FillColor = System.Drawing.Color.Silver;
            this.daUiButton31.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton31.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.Location = new System.Drawing.Point(106, 54);
            this.daUiButton31.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton31.Name = "daUiButton31";
            this.daUiButton31.PLC_Enable = true;
            this.daUiButton31.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton31.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton31.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton31.pLCBitselectRealize.BitPattern = false;
            this.daUiButton31.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton31.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton31.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton31.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton31.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton31.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton31.pLCBitselectRealize.OutReverse = false;
            this.daUiButton31.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton31.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton31.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton31.pLCBitselectRealize.ReadWriteAddress = "511.0";
            this.daUiButton31.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton31.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton31.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton31.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton31.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton31.pLCBitselectRealize.Speech = false;
            this.daUiButton31.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton31.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton31.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton31.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton31.pLCBitselectRealize.TextContent_0 = " 横向\n定位开";
            this.daUiButton31.pLCBitselectRealize.TextContent_1 = "  横向\n定位开中";
            this.daUiButton31.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton31.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton31.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton31.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton31.pLCBitselectRealize.TextState = 0;
            this.daUiButton31.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton31.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton31.pLCBitselectRealize.WriteAddress = "2.3";
            this.daUiButton31.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton31.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton31.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton31.Size = new System.Drawing.Size(105, 47);
            this.daUiButton31.TabIndex = 205;
            this.daUiButton31.Text = " 横向\n定位开";
            this.daUiButton31.Textalign_0 = "MiddleCenter";
            this.daUiButton31.Textalign_1 = "MiddleCenter";
            this.daUiButton31.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton31.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton31.TextContent_0 = " 横向\n定位开";
            this.daUiButton31.TextContent_1 = "  横向\n定位开中";
            this.daUiButton31.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton31.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton1
            // 
            this.daUiButton1.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton1.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton1.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton1.FillColor = System.Drawing.Color.Silver;
            this.daUiButton1.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton1.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.Location = new System.Drawing.Point(240, 54);
            this.daUiButton1.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton1.Name = "daUiButton1";
            this.daUiButton1.PLC_Enable = true;
            this.daUiButton1.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton1.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton1.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton1.pLCBitselectRealize.BitPattern = false;
            this.daUiButton1.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton1.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton1.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton1.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton1.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton1.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton1.pLCBitselectRealize.OutReverse = false;
            this.daUiButton1.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton1.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton1.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton1.pLCBitselectRealize.ReadWriteAddress = "511.1";
            this.daUiButton1.pLCBitselectRealize.ReadWriteFunction = "Q";
            this.daUiButton1.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton1.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton1.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton1.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton1.pLCBitselectRealize.Speech = false;
            this.daUiButton1.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton1.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton1.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton1.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton1.pLCBitselectRealize.TextContent_0 = " 横向\n定位关";
            this.daUiButton1.pLCBitselectRealize.TextContent_1 = "  横向\n定位关中";
            this.daUiButton1.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton1.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton1.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton1.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton1.pLCBitselectRealize.TextState = 0;
            this.daUiButton1.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton1.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton1.pLCBitselectRealize.WriteAddress = "2.4";
            this.daUiButton1.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton1.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton1.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton1.Size = new System.Drawing.Size(105, 47);
            this.daUiButton1.TabIndex = 206;
            this.daUiButton1.Text = " 横向\n定位关";
            this.daUiButton1.Textalign_0 = "MiddleCenter";
            this.daUiButton1.Textalign_1 = "MiddleCenter";
            this.daUiButton1.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton1.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton1.TextContent_0 = " 横向\n定位关";
            this.daUiButton1.TextContent_1 = "  横向\n定位关中";
            this.daUiButton1.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton1.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton4
            // 
            this.daUiButton4.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton4.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton4.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton4.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton4.FillColor = System.Drawing.Color.Silver;
            this.daUiButton4.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton4.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.Location = new System.Drawing.Point(594, 487);
            this.daUiButton4.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton4.Name = "daUiButton4";
            this.daUiButton4.PLC_Enable = true;
            this.daUiButton4.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton4.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton4.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.daUiButton4.pLCBitselectRealize.BitPattern = false;
            this.daUiButton4.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton4.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton4.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton4.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton4.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton4.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton4.pLCBitselectRealize.OutReverse = false;
            this.daUiButton4.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton4.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton4.pLCBitselectRealize.ReadWrite = true;
            this.daUiButton4.pLCBitselectRealize.ReadWriteAddress = "3.0";
            this.daUiButton4.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton4.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton4.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton4.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton4.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton4.pLCBitselectRealize.Speech = false;
            this.daUiButton4.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton4.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton4.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton4.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton4.pLCBitselectRealize.TextContent_0 = "回原位";
            this.daUiButton4.pLCBitselectRealize.TextContent_1 = "  原点\n回归完成";
            this.daUiButton4.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton4.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton4.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton4.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton4.pLCBitselectRealize.TextState = 0;
            this.daUiButton4.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton4.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton4.pLCBitselectRealize.WriteAddress = "2.2";
            this.daUiButton4.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton4.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton4.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton4.Size = new System.Drawing.Size(105, 47);
            this.daUiButton4.TabIndex = 208;
            this.daUiButton4.Text = "回原位";
            this.daUiButton4.Textalign_0 = "MiddleCenter";
            this.daUiButton4.Textalign_1 = "MiddleCenter";
            this.daUiButton4.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton4.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton4.TextContent_0 = "回原位";
            this.daUiButton4.TextContent_1 = "  原点\n回归完成";
            this.daUiButton4.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton4.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // daUiButton19
            // 
            this.daUiButton19.APLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLCSet.Set1;
            this.daUiButton19.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton19.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.daUiButton19.Cursor = System.Windows.Forms.Cursors.Hand;
            this.daUiButton19.FillColor = System.Drawing.Color.Silver;
            this.daUiButton19.FillHoverColor = System.Drawing.Color.Silver;
            this.daUiButton19.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.Location = new System.Drawing.Point(437, 487);
            this.daUiButton19.MinimumSize = new System.Drawing.Size(1, 1);
            this.daUiButton19.Name = "daUiButton19";
            this.daUiButton19.PLC_Enable = true;
            this.daUiButton19.pLCBitselectRealize.AwaitTime = 0;
            this.daUiButton19.pLCBitselectRealize.backgroundColor_0 = System.Drawing.Color.Silver;
            this.daUiButton19.pLCBitselectRealize.backgroundColor_1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.daUiButton19.pLCBitselectRealize.BitPattern = false;
            this.daUiButton19.pLCBitselectRealize.description = "PLCBitselectRealize";
            this.daUiButton19.pLCBitselectRealize.keyMinTime = 0;
            this.daUiButton19.pLCBitselectRealize.LoosenOut = false;
            this.daUiButton19.pLCBitselectRealize.NoAccessConceal = false;
            this.daUiButton19.pLCBitselectRealize.NoAccessForm = false;
            this.daUiButton19.pLCBitselectRealize.OperationAffirm = false;
            this.daUiButton19.pLCBitselectRealize.OutReverse = false;
            this.daUiButton19.pLCBitselectRealize.Pattern = PLC通讯基础控件项目.控件类基.控件数据结构.Button_pattern.Regression;
            this.daUiButton19.pLCBitselectRealize.PLCTimer = null;
            this.daUiButton19.pLCBitselectRealize.ReadWrite = false;
            this.daUiButton19.pLCBitselectRealize.ReadWriteAddress = "2.7";
            this.daUiButton19.pLCBitselectRealize.ReadWriteFunction = "M";
            this.daUiButton19.pLCBitselectRealize.ReadWritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton19.pLCBitselectRealize.SafetyBehaviorPattern = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyCategory = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyFunction = "M";
            this.daUiButton19.pLCBitselectRealize.SafetyPattern = 0;
            this.daUiButton19.pLCBitselectRealize.SafetyPLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Mitsubishi;
            this.daUiButton19.pLCBitselectRealize.Speech = false;
            this.daUiButton19.pLCBitselectRealize.Textalign_0 = "MiddleCenter";
            this.daUiButton19.pLCBitselectRealize.Textalign_1 = "MiddleCenter";
            this.daUiButton19.pLCBitselectRealize.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton19.pLCBitselectRealize.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton19.pLCBitselectRealize.TextContent_0 = "复位";
            this.daUiButton19.pLCBitselectRealize.TextContent_1 = "复位";
            this.daUiButton19.pLCBitselectRealize.Textflicker_0 = 0;
            this.daUiButton19.pLCBitselectRealize.Textflicker_1 = 0;
            this.daUiButton19.pLCBitselectRealize.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.pLCBitselectRealize.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.pLCBitselectRealize.TextItalic_0 = false;
            this.daUiButton19.pLCBitselectRealize.TextItalic_1 = false;
            this.daUiButton19.pLCBitselectRealize.TextState = 0;
            this.daUiButton19.pLCBitselectRealize.TextUnderline_0 = false;
            this.daUiButton19.pLCBitselectRealize.TextUnderline_1 = false;
            this.daUiButton19.pLCBitselectRealize.WriteAddress = "8131.0";
            this.daUiButton19.pLCBitselectRealize.WriteFunction = "M";
            this.daUiButton19.pLCBitselectRealize.WritePLC = PLC通讯基础控件项目.控件类基.控件数据结构.PLC.Siemens;
            this.daUiButton19.pLCBitselectRealize.WrSafetyAddress = "0";
            this.daUiButton19.Size = new System.Drawing.Size(105, 47);
            this.daUiButton19.TabIndex = 207;
            this.daUiButton19.Text = "复位";
            this.daUiButton19.Textalign_0 = "MiddleCenter";
            this.daUiButton19.Textalign_1 = "MiddleCenter";
            this.daUiButton19.TextColor_0 = System.Drawing.Color.White;
            this.daUiButton19.TextColor_1 = System.Drawing.Color.White;
            this.daUiButton19.TextContent_0 = "复位";
            this.daUiButton19.TextContent_1 = "复位";
            this.daUiButton19.TextFont_0 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.daUiButton19.TextFont_1 = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            // 
            // 新ZDP手动界面
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(897, 679);
            this.Name = "新ZDP手动界面";
            this.Text = "新ZDP界面";
            this.uiPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private 基础控件.DAUiButton daUiButton7;
        private 基础控件.DAUiButton daUiButton8;
        private 基础控件.DAUiButton daUiButton5;
        private 基础控件.DAUiButton daUiButton6;
        private 基础控件.DAUiButton daUiButton2;
        private 基础控件.DAUiButton daUiButton3;
        private 基础控件.DAUiButton daUiButton31;
        private 基础控件.DAUiButton daUiButton19;
        private 基础控件.DAUiButton daUiButton4;
        private 基础控件.DAUiButton daUiButton1;
    }
}